# -*- coding: utf-8 -*-
"""Copia de Expectativa de vida prueba- 29/04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UHqQShZm6T2YYM5szQdlGf9XGkBRueja
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df1 = pd.read_csv("Life Expectancy Data.csv")

df1 = df1.dropna(subset=['Life expectancy '])
df1 = df1[df1['Life expectancy '] != 0]

df1.columns = df1.columns.str.strip()

df1.head()

len(df1)

df1.columns

df1.shape

df1.describe()

df1.info()

df1.columns = df1.columns.str.strip()

df1["Life expectancy"].max()
print("El maximo de expectativa de vida:", df1["Life expectancy"].max())

df1["Life expectancy"].min()
print("El minimo de expectativa de vida:", df1["Life expectancy"].min())

"""**Código de abajo**. Agrupa el dataset según dos variables: la esperanza de vida ("Life expectancy") y el país ("Country"). Es decir, junta todas las filas que tienen el mismo valor de esperanza de vida y pertenecen al mismo país.

Luego, sobre cada grupo formado, aplica la función "count()", que cuenta cuántos valores NO nulos (no vacíos) hay en cada columna.

Por eso, los números que aparecen (1, 0, etc.) no son valores del dataset original, sino cantidades de datos disponibles dentro de cada grupo.
"""

df1.groupby(["Life expectancy" , "Country"]).count()

"""**Código de abajo.**Este código agrupa el dataset por país ("Country"), es decir, junta todas las filas que pertenecen al mismo país (por ejemplo, todos los años de Argentina, todos los años de Francia, etc.).
Luego selecciona solo dos variables: "Life expectancy" y "infant deaths".
Después aplica la función "nunique()", que cuenta cuántos valores distintos (únicos) hay en cada una de esas columnas dentro de cada país.

El resultado muestra, para cada país:
cuántos valores diferentes de esperanza de vida tuvo a lo largo del tiempo
cuántos valores diferentes de muertes infantiles tuvo
Por ejemplo:
Afghanistan → 14 en "Life expectancy"
significa que, a lo largo de los años, tuvo 14 valores distintos de esperanza de vida
Albania → 16
significa que en el dataset tiene 16 valores distintos (probablemente 16 años con datos distintos)
En general:
números altos → la variable cambia bastante a lo largo del tiempo en ese país
números bajos → la variable cambia poco o se repite
Importante:
Esto no cuenta cuántos datos hay, sino cuántos valores diferentes hay.
"""

df1.groupby('Country')[['Life expectancy', 'infant deaths']].nunique()

mean_study_hours = df1["Life expectancy"].mean()
print("El promedio de expectativa de vida es:", mean_study_hours)

df1.sort_values("Life expectancy", ascending=False).head()

df1.sort_values("Life expectancy", ascending=True).head()

df1.info()

"""Código de abajo. cuántas veces se repite cada país en el dataset (supongo que por años)"""

df1["Country"].value_counts()

"""**Código de abajo**. Este código toma la columna "Life expectancy" (esperanza de vida) y cuenta cuántas veces aparece cada valor dentro del dataset.

El resultado muestra una tabla donde:
a la izquierda están los valores de esperanza de vida
a la derecha está la cantidad de veces que aparece cada uno
Por ejemplo: 73.0 → 45 significa que el valor 73.0 aparece 45 veces en el dataset
75.0 → 33 significa que aparece 33 veces
83.4 → 1 significa que ese valor aparece una sola vez

En general
valores con números altos → son más comunes en el dataset
valores con 1 → son poco frecuentes o únicos
Importante:
Esto no agrupa por país ni por año, simplemente cuenta frecuencias totales en toda la base.
Sirve para entender:
qué valores de esperanza de vida son más frecuentes
cómo se distribuyen los datos
si hay valores raros o poco comunes
"""

df1["Life expectancy"].value_counts()

"""Código de abajo. Lo mismo que el value count de arriba solo que en relación a la mortalidad de adultos. 34 veces se repite el 12.0, 30 veces el 14.0 y así"""

df1["Adult Mortality"].value_counts()

df1['GDP (in thousands)'] = df1['GDP'] / 1000
display(df1[['Country', 'Year', 'GDP', 'GDP (in thousands)']].head())

"""Código de abajo. Este código selecciona tres columnas del dataset: el país ("Country"), los años de educación ("Schooling") y la tasa de HIV/AIDS.

Luego aplica la función "value_counts()", que cuenta cuántas veces aparece cada combinación exacta de esos tres valores.

Es decir, agrupa por combinaciones únicas de:
Country
Schooling
HIV/AIDS
y cuenta cuántas filas tienen exactamente esos mismos valores.

El resultado muestra:
cada combinación única de (Country, Schooling, HIV/AIDS)
cuántas veces se repite en el dataset
"""

df1[["Country" , "Schooling" , "HIV/AIDS"]].value_counts()

"""Código de abajo. Toma la columna Schooling (años de escolaridad) y usa cada valor distinto como criterio de agrupación del dataset.
El resultado muestra una tabla donde:

a la izquierda están los valores únicos de Schooling (por ejemplo 0.0, 10.5, 15.2, etc.)
a la derecha aparece, para cada columna del dataset, cuántos datos no nulos (no NaN) existen dentro de cada grupo de Schooling.

Es decir, NO cuenta cuántas veces aparece Schooling, sino que, para cada valor de Schooling, cuenta cuántos registros tienen datos válidos en cada variable.
Por ejemplo:
Schooling = 0.0
Life expectancy → 26
Alcohol → 17
GDP → 28

Esto significa que, para los países/años con escolaridad igual a 0.0:

hay 26 valores no nulos de esperanza de vida
solo 17 valores no nulos de alcohol
28 valores no nulos de GDP



Las diferencias entre columnas se deben a la presencia de datos faltantes (NaN).
En general:

números altos → esa variable tiene pocos o ningún dato faltante para ese nivel de Schooling
números más bajos → esa variable tiene muchos valores faltantes en ese grupo
"""

df1.groupby("Schooling").count()

"""Código de abajo. Este código filtra el dataset y se queda únicamente con las filas donde la esperanza de vida (Life expectancy) es menor a 50.
El resultado muestra:

países y años con niveles muy bajos de esperanza de vida
todas las columnas originales del dataset
solo los casos que cumplen esa condición

En general:

valores menores a 50 → países con situaciones sanitarias críticas
valores muy bajos → posibles crisis, epidemias o contextos de extrema pobreza

Importante:

no agrupa países
un mismo país puede aparecer varias veces (uno por cada año)
"""

df1[df1['Life expectancy']< 50.0]

"""Código de abajo. Agrupa el dataset por país y calcula el promedio de la esperanza de vida y de los años de escolaridad para cada país.
El resultado muestra una tabla donde: a la izquierda están los países
a la derecha aparecen:
el promedio de Life expectancy
el promedio de Schooling
Cada fila representa un país, no un país por año.
Cómo funciona el código paso a paso
groupby("Country")
agrupa todas las filas que pertenecen al mismo país, sin importar el año.
Es decir:
junta todos los registros de Afghanistan
junta todos los registros de Albania
y así con cada país
.agg({...})
indica qué operación estadística se quiere hacer sobre cada columna.
"Life expectancy": "mean"
calcula la esperanza de vida promedio del país considerando todos los años disponibles
"Schooling": "mean"
calcula el promedio de años de escolaridad del país, también usando todos los años.
"""

df1.groupby("Country").agg({"Life expectancy":"mean", "Schooling":"mean"})

"""Código de abajo. agrupa el dataset por país y calcula el promedio de HIV/AIDS, años de escolaridad y GDP para cada país.
El resultado muestra una tabla donde:

a la izquierda están los países
a la derecha aparecen:

el promedio de HIV/AIDS
el promedio de Schooling
el promedio de GDP
Cada fila representa un país, no un país por año
Cómo funciona el código paso a paso
groupby("Country")
agrupa todas las filas que pertenecen al mismo país, juntando todos los años disponibles de ese país.
.agg({...})
permite aplicar distintas operaciones estadísticas a distintas columnas al mismo tiempo.
"HIV/AIDS": "mean"
calcula el valor promedio de HIV/AIDS del país considerando todos los años.
"Schooling": "mean"
calcula el promedio de años de escolaridad del país a lo largo del tiempo.
"GDP": "mean"
calcula el GDP promedio del país considerando todos los registros disponibles.
"""

df1.groupby("Country").agg({"HIV/AIDS":"mean", "Schooling":"mean", "GDP":"mean"})

import matplotlib.pyplot as plt
from google.colab import files

df1.plot(kind="scatter", x="Schooling", y="Life expectancy")
plt.title("Life Expectancy vs Schooling")
plt.xlabel("Schooling") # Ensure xlabel is set for clarity
plt.ylabel("Life expectancy") # Corrected column name
plt.show()

# 1. Guardar el gráfico como imagen PNG
# El dpi=300 hace que tenga calidad "HD" para que no se vea borroso en la presentación.
# El bbox_inches='tight' recorta los bordes blancos extra.
plt.savefig("grafico_schooling.png", dpi=300, bbox_inches='tight')

# 2. Descargar el archivo a tu compu
files.download("grafico_schooling.png")

import matplotlib.pyplot as plt
plt.scatter(df1[" HIV/AIDS"], df1["Life expectancy "])
plt.xlabel("HIV/AIDS")
plt.ylabel("Life expectancy ")
plt.title("Life expectancy vs HIV/AIDS")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

sns.regplot(x="Adult Mortality", y="Life expectancy ", data=df1 , color="yellow")
plt.title("Life expectancy vs Adult Mortality")
plt.show()

import matplotlib.pyplot as plt
plt.scatter(df1["GDP"], df1["Life expectancy "], color="purple")
plt.xlabel("GDP")
plt.ylabel("Life expectancy ")
plt.title("Life expectancy vs GDP")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

sns.regplot(x="infant deaths", y="Life expectancy ", data=df1, color='orange')
plt.title("Expectativa de vida vs Mortalidad Infantil")
plt.show()

plt.scatter(df1["Income composition of resources"], df1["Life expectancy"], color='red')
plt.xlabel("Income composition")
plt.ylabel("Life expectancy")
plt.title("Life expectancy vs Income composition")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
import requests
from io import BytesIO

# 1. Cargar dataset
df1 = pd.read_csv("Life Expectancy Data con united kingdom.csv")

# 2. Filtrar año 2015 y limpiar datos
df1_2015 = df1[df1['Year'] == 2015].dropna(subset=['Life expectancy '])

# 3. Ordenar por expectativa de vida (descendente) y tomar top 30
df1_top30 = df1_2015.sort_values(by='Life expectancy ', ascending=False).head(30)

countries = df1_top30['Country'].tolist()
life_exp = df1_top30['Life expectancy '].tolist()

# 4. Diccionario de banderas (FlagCDN) con nombres exactos del dataset
flag_urls = {
    "Japan": "https://flagcdn.com/w320/jp.png",
    "Switzerland": "https://flagcdn.com/w320/ch.png",
    "Australia": "https://flagcdn.com/w320/au.png",
    "Spain": "https://flagcdn.com/w320/es.png",
    "Italy": "https://flagcdn.com/w320/it.png",
    "France": "https://flagcdn.com/w320/fr.png",
    "Sweden": "https://flagcdn.com/w320/se.png",
    "Norway": "https://flagcdn.com/w320/no.png",
    "Netherlands": "https://flagcdn.com/w320/nl.png",
    "United Kingdom": "https://flagcdn.com/w320/gb.png",
    "Germany": "https://flagcdn.com/w320/de.png",
    "Canada": "https://flagcdn.com/w320/ca.png",
    "New Zealand": "https://flagcdn.com/w320/nz.png",
    "Austria": "https://flagcdn.com/w320/at.png",
    "Belgium": "https://flagcdn.com/w320/be.png",
    "Denmark": "https://flagcdn.com/w320/dk.png",
    "Finland": "https://flagcdn.com/w320/fi.png",
    "Ireland": "https://flagcdn.com/w320/ie.png",
    "Portugal": "https://flagcdn.com/w320/pt.png",
    "Greece": "https://flagcdn.com/w320/gr.png",
    "Israel": "https://flagcdn.com/w320/il.png",
    "Iceland": "https://flagcdn.com/w320/is.png",
    "Singapore": "https://flagcdn.com/w320/sg.png",
    "Republic of Korea": "https://flagcdn.com/w320/kr.png",
    "Slovenia": "https://flagcdn.com/w320/si.png",
    "Luxembourg": "https://flagcdn.com/w320/lu.png",
    "Malta": "https://flagcdn.com/w320/mt.png",
    "Cyprus": "https://flagcdn.com/w320/cy.png",
    "Costa Rica": "https://flagcdn.com/w320/cr.png",
    "Chile": "https://flagcdn.com/w320/cl.png"
}

# 5. Función para obtener banderas
def get_flag(country):
    try:
        url = flag_urls[country]
        response = requests.get(url, timeout=5)
        img = Image.open(BytesIO(response.content))
        return img
    except:
        return None

# 6. Crear figura
plt.figure(figsize=(14, 10))

# 7. Dibujar "barras" con banderas + recuadro negro + texto
for i, country in enumerate(countries):
    img = get_flag(country)
    if img:
        bar_width = int(life_exp[i] * 6)   # ancho proporcional
        img = img.resize((bar_width, 25)) # altura fija
        # ✅ ya no aplicamos flips, solo origin="upper"
        plt.imshow(
            img,
            extent=[0, life_exp[i], i - 0.4, i + 0.4],
            aspect='auto',
            origin="lower"
        )
        # Recuadro negro alrededor de la barra
        plt.plot([0, life_exp[i], life_exp[i], 0, 0],
                 [i - 0.4, i - 0.4, i + 0.4, i + 0.4, i - 0.4],
                 color="black", linewidth=1)

        # Número exacto al final de la barra
        plt.text(
            life_exp[i] + 0.5, i, f"{life_exp[i]:.1f}",
            va='center', ha='left', fontsize=9, color="black"
        )

# 8. Ejes y etiquetas
plt.yticks(range(len(countries)), countries, fontsize=9)
plt.xlabel("Expectativa de vida")
plt.title("Top 30 países con mayor expectativa de vida (2015) - Banderas orientadas correctamente")

plt.gca().invert_yaxis()
plt.xlim(0, max(life_exp) + 5)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
import requests
from io import BytesIO


# 2. Filtrar año 2015 y limpiar datos
df1_2015 = df1[df1['Year'] == 2015].dropna(subset=['Life expectancy '])

# 3. Ordenar por expectativa de vida (descendente) y tomar top 30
df1_top30 = df1_2015.sort_values(by='Life expectancy ', ascending=False).head(30)

countries = df1_top30['Country'].tolist()
life_exp = df1_top30['Life expectancy '].tolist()

# 4. Diccionario de banderas (FlagCDN) con nombres exactos del dataset
flag_urls = {
    "Japan": "https://flagcdn.com/w320/jp.png",
    "Switzerland": "https://flagcdn.com/w320/ch.png",
    "Australia": "https://flagcdn.com/w320/au.png",
    "Spain": "https://flagcdn.com/w320/es.png",
    "Italy": "https://flagcdn.com/w320/it.png",
    "France": "https://flagcdn.com/w320/fr.png",
    "Sweden": "https://flagcdn.com/w320/se.png",
    "Norway": "https://flagcdn.com/w320/no.png",
    "Netherlands": "https://flagcdn.com/w320/nl.png",
    "United Kingdom": "https://flagcdn.com/w320/gb.png",
    "Germany": "https://flagcdn.com/w320/de.png",
    "Canada": "https://flagcdn.com/w320/ca.png",
    "New Zealand": "https://flagcdn.com/w320/nz.png",
    "Austria": "https://flagcdn.com/w320/at.png",
    "Belgium": "https://flagcdn.com/w320/be.png",
    "Denmark": "https://flagcdn.com/w320/dk.png",
    "Finland": "https://flagcdn.com/w320/fi.png",
    "Ireland": "https://flagcdn.com/w320/ie.png",
    "Portugal": "https://flagcdn.com/w320/pt.png",
    "Greece": "https://flagcdn.com/w320/gr.png",
    "Israel": "https://flagcdn.com/w320/il.png",
    "Iceland": "https://flagcdn.com/w320/is.png",
    "Singapore": "https://flagcdn.com/w320/sg.png",
    "Republic of Korea": "https://flagcdn.com/w320/kr.png",
    "Slovenia": "https://flagcdn.com/w320/si.png",
    "Luxembourg": "https://flagcdn.com/w320/lu.png",
    "Malta": "https://flagcdn.com/w320/mt.png",
    "Cyprus": "https://flagcdn.com/w320/cy.png",
    "Costa Rica": "https://flagcdn.com/w320/cr.png",
    "Chile": "https://flagcdn.com/w320/cl.png"
}

# 5. Función para obtener banderas normalizadas (sin deformación)
TARGET_W = 320
TARGET_H = 160  # ratio 2:1

def get_flag(country):
    try:
        url = flag_urls[country]
        response = requests.get(url, timeout=5)
        img = Image.open(BytesIO(response.content)).convert("RGBA")
        img.thumbnail((TARGET_W, TARGET_H), Image.LANCZOS)
        canvas = Image.new("RGBA", (TARGET_W, TARGET_H), (255, 255, 255, 255))
        offset_x = (TARGET_W - img.width) // 2
        offset_y = (TARGET_H - img.height) // 2
        canvas.paste(img, (offset_x, offset_y))
        return canvas
    except:
        return None

# 6. Crear figura
plt.figure(figsize=(14, 10))

# 7. Dibujar barras con banderas + recuadro negro + texto
bar_height = 0.75

for i, country in enumerate(countries):
    img = get_flag(country)
    if img:
        plt.imshow(
            img,
            extent=[0, life_exp[i], i - bar_height/2, i + bar_height/2],
            aspect='auto',
            origin='upper'
        )
        plt.plot([0, life_exp[i], life_exp[i], 0, 0],
                 [i - bar_height/2, i - bar_height/2, i + bar_height/2, i + bar_height/2, i - bar_height/2],
                 color="black", linewidth=1)
        plt.text(
            life_exp[i] + 0.5, i, f"{life_exp[i]:.1f}",
            va='center', ha='left', fontsize=9, color="black"
        )

# 8. Ejes y etiquetas
plt.yticks(range(len(countries)), countries, fontsize=9)
plt.xlabel("Expectativa de vida")
plt.title("Top 30 países con mayor expectativa de vida (2015)")

plt.gca().invert_yaxis()
plt.xlim(0, max(life_exp) + 5)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.offsetbox import OffsetImage, AnnotationBbox
from PIL import Image
import requests
from io import BytesIO
import numpy as np

# 2. Filtrar año 2015 y limpiar datos
df1_2015 = df1[df1['Year'] == 2015].dropna(subset=['Life expectancy '])

# 3. Ordenar por expectativa de vida (descendente) y tomar top 30
df1_top30 = df1_2015.sort_values(by='Life expectancy ', ascending=False).head(30)

countries = df1_top30['Country'].tolist()
life_exp = df1_top30['Life expectancy '].tolist()

# 4. Diccionario de banderas
flag_urls = {
    "Japan": "https://flagcdn.com/w320/jp.png",
    "Switzerland": "https://flagcdn.com/w320/ch.png",
    "Australia": "https://flagcdn.com/w320/au.png",
    "Spain": "https://flagcdn.com/w320/es.png",
    "Italy": "https://flagcdn.com/w320/it.png",
    "France": "https://flagcdn.com/w320/fr.png",
    "Sweden": "https://flagcdn.com/w320/se.png",
    "Norway": "https://flagcdn.com/w320/no.png",
    "Netherlands": "https://flagcdn.com/w320/nl.png",
    "United Kingdom": "https://flagcdn.com/w320/gb.png",
    "Germany": "https://flagcdn.com/w320/de.png",
    "Canada": "https://flagcdn.com/w320/ca.png",
    "New Zealand": "https://flagcdn.com/w320/nz.png",
    "Austria": "https://flagcdn.com/w320/at.png",
    "Belgium": "https://flagcdn.com/w320/be.png",
    "Denmark": "https://flagcdn.com/w320/dk.png",
    "Finland": "https://flagcdn.com/w320/fi.png",
    "Ireland": "https://flagcdn.com/w320/ie.png",
    "Portugal": "https://flagcdn.com/w320/pt.png",
    "Greece": "https://flagcdn.com/w320/gr.png",
    "Israel": "https://flagcdn.com/w320/il.png",
    "Iceland": "https://flagcdn.com/w320/is.png",
    "Singapore": "https://flagcdn.com/w320/sg.png",
    "Republic of Korea": "https://flagcdn.com/w320/kr.png",
    "Slovenia": "https://flagcdn.com/w320/si.png",
    "Luxembourg": "https://flagcdn.com/w320/lu.png",
    "Malta": "https://flagcdn.com/w320/mt.png",
    "Cyprus": "https://flagcdn.com/w320/cy.png",
    "Costa Rica": "https://flagcdn.com/w320/cr.png",
    "Chile": "https://flagcdn.com/w320/cl.png"
}

# 5. Función para obtener bandera como array
def get_flag(country):
    try:
        url = flag_urls[country]
        response = requests.get(url, timeout=5)
        img = Image.open(BytesIO(response.content)).convert("RGB")
        img = img.resize((80, 50), Image.LANCZOS)  # tamaño fijo con buen ratio
        return np.array(img)
    except:
        return None

# 6. Crear figura y eje
fig, ax = plt.subplots(figsize=(14, 12))

min_val = min(life_exp)

for i, country in enumerate(countries):
    # Barra de fondo gris
    ax.barh(i, life_exp[i], color="#e0e0e0", edgecolor="black", linewidth=0.8, height=0.7)

    # Bandera pegada al inicio de la barra (esquina izquierda)
    img_arr = get_flag(country)
    if img_arr is not None:
        im = OffsetImage(img_arr, zoom=0.55)
        ab = AnnotationBbox(
            im,
            (min_val + 0.3, i),   # posición: pegada al inicio de la barra
            frameon=True,
            box_alignment=(0, 0.5),
            bboxprops=dict(edgecolor="black", linewidth=0.8)
        )
        ax.add_artist(ab)

    # Valor al final de la barra
    ax.text(life_exp[i] + 0.2, i, f"{life_exp[i]:.1f}",
            va='center', ha='left', fontsize=9)

# 7. Ejes y formato
ax.set_yticks(range(len(countries)))
ax.set_yticklabels(countries, fontsize=9)
ax.set_xlabel("Expectativa de vida (años)", fontsize=11)
ax.set_title("Top 30 países con mayor expectativa de vida (2015)", fontsize=13, fontweight='bold')
ax.invert_yaxis()
ax.set_xlim(0, max(life_exp) + 5)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.offsetbox import OffsetImage, AnnotationBbox
from PIL import Image
import requests
from io import BytesIO
import numpy as np

# 2. Filtrar año 2015 y limpiar datos
df1_2015 = df1[df1['Year'] == 2015].dropna(subset=['Life expectancy'])

# 3. Ordenar por expectativa de vida (descendente) y tomar top 30
df1_top30 = df1_2015.sort_values(by='Life expectancy', ascending=False).head(30)

countries = df1_top30['Country'].tolist()
life_exp = df1_top30['Life expectancy'].tolist()

# 4. Diccionario de banderas
flag_urls = {
    "Japan": "https://flagcdn.com/w320/jp.png",
    "Switzerland": "https://flagcdn.com/w320/ch.png",
    "Australia": "https://flagcdn.com/w320/au.png",
    "Spain": "https://flagcdn.com/w320/es.png",
    "Italy": "https://flagcdn.com/w320/it.png",
    "France": "https://flagcdn.com/w320/fr.png",
    "Sweden": "https://flagcdn.com/w320/se.png",
    "Norway": "https://flagcdn.com/w320/no.png",
    "Netherlands": "https://flagcdn.com/w320/nl.png",
    "United Kingdom": "https://flagcdn.com/w320/gb.png",
    "Germany": "https://flagcdn.com/w320/de.png",
    "Canada": "https://flagcdn.com/w320/ca.png",
    "New Zealand": "https://flagcdn.com/w320/nz.png",
    "Austria": "https://flagcdn.com/w320/at.png",
    "Belgium": "https://flagcdn.com/w320/be.png",
    "Denmark": "https://flagcdn.com/w320/dk.png",
    "Finland": "https://flagcdn.com/w320/fi.png",
    "Ireland": "https://flagcdn.com/w320/ie.png",
    "Portugal": "https://flagcdn.com/w320/pt.png",
    "Greece": "https://flagcdn.com/w320/gr.png",
    "Israel": "https://flagcdn.com/w320/il.png",
    "Iceland": "https://flagcdn.com/w320/is.png",
    "Singapore": "https://flagcdn.com/w320/sg.png",
    "Republic of Korea": "https://flagcdn.com/w320/kr.png",
    "Slovenia": "https://flagcdn.com/w320/si.png",
    "Luxembourg": "https://flagcdn.com/w320/lu.png",
    "Malta": "https://flagcdn.com/w320/mt.png",
    "Cyprus": "https://flagcdn.com/w320/cy.png",
    "Costa Rica": "https://flagcdn.com/w320/cr.png",
    "Chile": "https://flagcdn.com/w320/cl.png"
}

# 5. Función: descarga bandera, saca color dominante y miniatura
def get_flag_data(country):
    try:
        url = flag_urls[country]
        response = requests.get(url, timeout=5)
        img = Image.open(BytesIO(response.content)).convert("RGB")

        # Color dominante (promedio excluyendo píxeles muy claros/oscuros)
        arr = np.array(img).reshape(-1, 3).astype(float)
        brightness = arr.mean(axis=1)
        mask = (brightness > 30) & (brightness < 220)
        filtered = arr[mask] if mask.sum() > 0 else arr
        dominant = tuple((filtered.mean(axis=0) / 255).tolist())

        # Miniatura para poner al costado
        thumb = img.resize((60, 38), Image.LANCZOS)
        return dominant, np.array(thumb)
    except:
        return (0.6, 0.6, 0.6), None

# 6. Pre-cargar banderas
print("Descargando banderas...")
flag_data = {c: get_flag_data(c) for c in countries}
print("Listo!")

# 7. Crear figura con margen izquierdo para las banderas
fig, ax = plt.subplots(figsize=(14, 12))
plt.subplots_adjust(left=0.28)

for i, country in enumerate(countries):
    color, thumb = flag_data[country]

    # Barra con color dominante de la bandera
    ax.barh(i, life_exp[i], color=color, edgecolor="black", linewidth=0.8, height=0.7)

    # Valor al final de la barra
    ax.text(life_exp[i] + 0.2, i, f"{life_exp[i]:.1f}",
            va='center', ha='left', fontsize=9)

    # Bandera a la izquierda del nombre del país
    if thumb is not None:
        im = OffsetImage(thumb, zoom=0.55)
        ab = AnnotationBbox(
            im,
            xy=(0, i),
            xycoords=('axes fraction', 'data'),
            box_alignment=(1.15, 0.5),
            frameon=True,
            bboxprops=dict(edgecolor="gray", linewidth=0.6)
        )
        ax.add_artist(ab)

# 8. Ejes y formato
ax.set_yticks(range(len(countries)))
ax.set_yticklabels(countries, fontsize=9)
ax.set_xlabel("Expectativa de vida (años)", fontsize=11)
ax.set_title("Top 30 países con mayor expectativa de vida (2015)", fontsize=13, fontweight='bold')
ax.invert_yaxis()
ax.set_xlim(0, max(life_exp) + 5)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.show()

import matplotlib.pyplot as plt
from matplotlib.offsetbox import OffsetImage, AnnotationBbox
from PIL import Image
import requests
from io import BytesIO
import numpy as np

# 2. Filtrar año 2015 y limpiar datos
df1_2015 = df1[df1['Year'] == 2015].dropna(subset=['Life expectancy '])

# 3. Ordenar por expectativa de vida (descendente) y tomar top 30
df1_top30 = df1_2015.sort_values(by='Life expectancy ', ascending=False).head(30)

countries = df1_top30['Country'].tolist()
life_exp = df1_top30['Life expectancy '].tolist()

# 4. Diccionario de banderas
flag_urls = {
    "Japan": "https://flagcdn.com/w320/jp.png",
    "Switzerland": "https://flagcdn.com/w320/ch.png",
    "Australia": "https://flagcdn.com/w320/au.png",
    "Spain": "https://flagcdn.com/w320/es.png",
    "Italy": "https://flagcdn.com/w320/it.png",
    "France": "https://flagcdn.com/w320/fr.png",
    "Sweden": "https://flagcdn.com/w320/se.png",
    "Norway": "https://flagcdn.com/w320/no.png",
    "Netherlands": "https://flagcdn.com/w320/nl.png",
    "United Kingdom": "https://flagcdn.com/w320/gb.png",
    "Germany": "https://flagcdn.com/w320/de.png",
    "Canada": "https://flagcdn.com/w320/ca.png",
    "New Zealand": "https://flagcdn.com/w320/nz.png",
    "Austria": "https://flagcdn.com/w320/at.png",
    "Belgium": "https://flagcdn.com/w320/be.png",
    "Denmark": "https://flagcdn.com/w320/dk.png",
    "Finland": "https://flagcdn.com/w320/fi.png",
    "Ireland": "https://flagcdn.com/w320/ie.png",
    "Portugal": "https://flagcdn.com/w320/pt.png",
    "Greece": "https://flagcdn.com/w320/gr.png",
    "Israel": "https://flagcdn.com/w320/il.png",
    "Iceland": "https://flagcdn.com/w320/is.png",
    "Singapore": "https://flagcdn.com/w320/sg.png",
    "Republic of Korea": "https://flagcdn.com/w320/kr.png",
    "Slovenia": "https://flagcdn.com/w320/si.png",
    "Luxembourg": "https://flagcdn.com/w320/lu.png",
    "Malta": "https://flagcdn.com/w320/mt.png",
    "Cyprus": "https://flagcdn.com/w320/cy.png",
    "Costa Rica": "https://flagcdn.com/w320/cr.png",
    "Chile": "https://flagcdn.com/w320/cl.png"
}

# 5. Color principal real de cada bandera
flag_colors = {
    "Japan":            "#BC002D",
    "Switzerland":      "#FF0000",
    "Australia":        "#00008B",
    "Spain":            "#c60b1e",
    "Italy":            "#009246",
    "France":           "#002395",
    "Sweden":           "#006AA7",
    "Norway":           "#EF2B2D",
    "Netherlands":      "#AE1C28",
    "United Kingdom":   "#012169",
    "Germany":          "#000000",
    "Canada":           "#FF0000",
    "New Zealand":      "#00247D",
    "Austria":          "#ED2939",
    "Belgium":          "#000000",
    "Denmark":          "#C60C30",
    "Finland":          "#003580",
    "Ireland":          "#169B62",
    "Portugal":         "#006600",
    "Greece":           "#0D5EAF",
    "Israel":           "#0038B8",
    "Iceland":          "#003897",
    "Singapore":        "#EF3340",
    "Republic of Korea":"#CD2E3A",
    "Slovenia":         "#003DA5",
    "Luxembourg":       "#EF3340",
    "Malta":            "#CF142B",
    "Cyprus":           "#4E90A0",
    "Costa Rica":       "#002B7F",
    "Chile":            "#D52B1E",
}

# 6. Función para obtener miniatura de bandera
def get_flag(country):
    try:
        url = flag_urls[country]
        response = requests.get(url, timeout=5)
        img = Image.open(BytesIO(response.content)).convert("RGB")
        img = img.resize((60, 38), Image.LANCZOS)
        return np.array(img)
    except:
        return None

# 7. Pre-cargar miniaturas
print("Descargando banderas...")
flag_thumbs = {c: get_flag(c) for c in countries}
print("Listo!")

# 8. Figura — margen derecho amplio para banderas
fig, ax = plt.subplots(figsize=(16, 12))
plt.subplots_adjust(right=0.82)  # espacio a la derecha para las banderas

for i, country in enumerate(countries):
    color = flag_colors.get(country, "#888888")
    thumb = flag_thumbs[country]

    # Barra con color real de la bandera
    ax.barh(i, life_exp[i], color=color, edgecolor="black", linewidth=0.8, height=0.7)

    # Valor numérico al final de la barra
    ax.text(life_exp[i] + 0.2, i, f"{life_exp[i]:.1f}",
            va='center', ha='left', fontsize=9)

    # Bandera a la derecha del número
    if thumb is not None:
        im = OffsetImage(thumb, zoom=0.6)
        ab = AnnotationBbox(
            im,
            xy=(1, i),
            xycoords=('axes fraction', 'data'),
            box_alignment=(-0.2, 0.5),
            frameon=True,
            bboxprops=dict(edgecolor="gray", linewidth=0.6)
        )
        ax.add_artist(ab)

# 9. Ejes y formato
ax.set_yticks(range(len(countries)))
ax.set_yticklabels(countries, fontsize=9)
ax.set_xlabel("Expectativa de vida (años)", fontsize=11)
ax.set_title("Top 30 países con mayor expectativa de vida (2015)", fontsize=13, fontweight='bold')
ax.invert_yaxis()
ax.set_xlim(0, max(life_exp) + 5)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.show()

import matplotlib.pyplot as plt
from matplotlib.offsetbox import OffsetImage, AnnotationBbox
from PIL import Image
import requests
from io import BytesIO
import numpy as np

# 2. Filtrar año 2015 y limpiar datos
df1_2015 = df1[df1['Year'] == 2015].dropna(subset=['Life expectancy '])

# 3. Ordenar ASCENDENTE y tomar los 30 con MENOR expectativa de vida
df1_bottom30 = df1_2015.sort_values(by='Life expectancy ', ascending=True).head(30)

countries = df1_bottom30['Country'].tolist()
life_exp = df1_bottom30['Life expectancy '].tolist()

# 4. Diccionario de banderas
flag_urls = {
    "Sierra Leone": "https://flagcdn.com/w320/sl.png",
    "Central African Republic": "https://flagcdn.com/w320/cf.png",
    "Chad": "https://flagcdn.com/w320/td.png",
    "Nigeria": "https://flagcdn.com/w320/ng.png",
    "Lesotho": "https://flagcdn.com/w320/ls.png",
    "Côte d'Ivoire": "https://flagcdn.com/w320/ci.png",
    "Swaziland": "https://flagcdn.com/w320/sz.png",
    "Angola": "https://flagcdn.com/w320/ao.png",
    "Cameroon": "https://flagcdn.com/w320/cm.png",
    "Somalia": "https://flagcdn.com/w320/so.png",
    "Guinea-Bissau": "https://flagcdn.com/w320/gw.png",
    "Mozambique": "https://flagcdn.com/w320/mz.png",
    "Mali": "https://flagcdn.com/w320/ml.png",
    "Zambia": "https://flagcdn.com/w320/zm.png",
    "Burkina Faso": "https://flagcdn.com/w320/bf.png",
    "Uganda": "https://flagcdn.com/w320/ug.png",
    "Malawi": "https://flagcdn.com/w320/mw.png",
    "Guinea": "https://flagcdn.com/w320/gn.png",
    "Congo": "https://flagcdn.com/w320/cg.png",
    "South Sudan": "https://flagcdn.com/w320/ss.png",
    "Burundi": "https://flagcdn.com/w320/bi.png",
    "Niger": "https://flagcdn.com/w320/ne.png",
    "Benin": "https://flagcdn.com/w320/bj.png",
    "Equatorial Guinea": "https://flagcdn.com/w320/gq.png",
    "Côte d'Ivoire": "https://flagcdn.com/w320/ci.png",
    "Haiti": "https://flagcdn.com/w320/ht.png",
    "Democratic Republic of the Congo": "https://flagcdn.com/w320/cd.png",
    "Namibia": "https://flagcdn.com/w320/na.png",
    "Togo": "https://flagcdn.com/w320/tg.png",
    "Zimbabwe": "https://flagcdn.com/w320/zw.png",
}

# 5. Color principal real de cada bandera
flag_colors = {
    "Sierra Leone":                     "#1EB53A",
    "Central African Republic":         "#003082",
    "Chad":                             "#002664",
    "Nigeria":                          "#008751",
    "Lesotho":                          "#009543",
    "Côte d'Ivoire":                    "#F77F00",
    "Swaziland":                        "#3E5EB9",
    "Angola":                           "#CC0000",
    "Cameroon":                         "#007A5E",
    "Somalia":                          "#4189DD",
    "Guinea-Bissau":                    "#CE1126",
    "Mozambique":                       "#009A44",
    "Mali":                             "#14B53A",
    "Zambia":                           "#198A00",
    "Burkina Faso":                     "#EF2B2D",
    "Uganda":                           "#000000",
    "Malawi":                           "#000000",
    "Guinea":                           "#CE1126",
    "Congo":                            "#009543",
    "South Sudan":                      "#078930",
    "Burundi":                          "#CE1126",
    "Niger":                            "#E05206",
    "Benin":                            "#008751",
    "Equatorial Guinea":                "#3E9A00",
    "Haiti":                            "#00209F",
    "Democratic Republic of the Congo": "#007FFF",
    "Namibia":                          "#003580",
    "Togo":                             "#006A4E",
    "Zimbabwe":                         "#006400",
    "Lesotho":                          "#009543",
}

# 6. Función para obtener miniatura de bandera
def get_flag(country):
    try:
        url = flag_urls[country]
        response = requests.get(url, timeout=5)
        img = Image.open(BytesIO(response.content)).convert("RGB")
        img = img.resize((60, 38), Image.LANCZOS)
        return np.array(img)
    except:
        return None

# 7. Pre-cargar miniaturas
print("Descargando banderas...")
flag_thumbs = {c: get_flag(c) for c in countries}
print("Listo!")

# 8. Figura
fig, ax = plt.subplots(figsize=(16, 12))
plt.subplots_adjust(right=0.82)

for i, country in enumerate(countries):
    color = flag_colors.get(country, "#888888")
    thumb = flag_thumbs[country]

    ax.barh(i, life_exp[i], color=color, edgecolor="black", linewidth=0.8, height=0.7)

    ax.text(life_exp[i] + 0.2, i, f"{life_exp[i]:.1f}",
            va='center', ha='left', fontsize=9)

    if thumb is not None:
        im = OffsetImage(thumb, zoom=0.6)
        ab = AnnotationBbox(
            im,
            xy=(1, i),
            xycoords=('axes fraction', 'data'),
            box_alignment=(-0.2, 0.5),
            frameon=True,
            bboxprops=dict(edgecolor="gray", linewidth=0.6)
        )
        ax.add_artist(ab)

# 9. Ejes y formato
ax.set_yticks(range(len(countries)))
ax.set_yticklabels(countries, fontsize=9)
ax.set_xlabel("Expectativa de vida (años)", fontsize=11)
ax.set_title("Top 30 países con menor expectativa de vida (2015)", fontsize=13, fontweight='bold')
ax.invert_yaxis()
ax.set_xlim(0, max(life_exp) + 5)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.show()

import matplotlib.pyplot as plt
from matplotlib.offsetbox import OffsetImage, AnnotationBbox
from PIL import Image
import requests
from io import BytesIO
import numpy as np
import pandas as pd # Import pandas

# Load df1 inside this cell to ensure it's defined
df1 = pd.read_csv("Life Expectancy Data.csv")

# Strip whitespace from column names
df1.columns = df1.columns.str.strip()

# 2. Filtrar año 2015 y limpiar datos
df1_2015 = df1[df1['Year'] == 2015].dropna(subset=['Life expectancy'])

# Normalizar nombre
df1_2015['Country'] = df1_2015['Country'].str.strip()
df1_2015['Country'] = df1_2015['Country'].replace({
    "Côte d'Ivoire": "Cote d'Ivoire"
})

# 3. Ordenar ASCENDENTE (menor a mayor) y tomar 30
df1_bottom30 = df1_2015.sort_values(by='Life expectancy', ascending=True).head(30)
countries = df1_bottom30['Country'].tolist()
life_exp = df1_bottom30['Life expectancy'].tolist()

# 4. Diccionario de banderas
flag_urls = {
    "Sierra Leone": "https://flagcdn.com/w320/sl.png",
    "Central African Republic": "https://flagcdn.com/w320/cf.png",
    "Lesotho": "https://flagcdn.com/w320/ls.png",
    "Nigeria": "https://flagcdn.com/w320/ng.png",
    "Chad": "https://flagcdn.com/w320/td.png",
    "Cote d'Ivoire": "https://flagcdn.com/w320/ci.png",
    "Guinea-Bissau": "https://flagcdn.com/w320/gw.png",
    "Somalia": "https://flagcdn.com/w320/so.png",
    "South Sudan": "https://flagcdn.com/w320/ss.png",
    "Zimbabwe": "https://flagcdn.com/w320/zw.png",
    "Burundi": "https://flagcdn.com/w320/bi.png",
    "Mali": "https://flagcdn.com/w320/ml.png",
    "Cameroon": "https://flagcdn.com/w320/cm.png",
    "Mozambique": "https://flagcdn.com/w320/mz.png",
    "Democratic Republic of the Congo": "https://flagcdn.com/w320/cd.png",
    "Equatorial Guinea": "https://flagcdn.com/w320/gq.png",
    "Guinea": "https://flagcdn.com/w320/gn.png",
    "Benin": "https://flagcdn.com/w320/bj.png",
    "Burkina Faso": "https://flagcdn.com/w320/bf.png",
    "Uganda": "https://flagcdn.com/w320/ug.png",
    "Zambia": "https://flagcdn.com/w320/zm.png",
    "Niger": "https://flagcdn.com/w320/ne.png",
    "Angola": "https://flagcdn.com/w320/ao.png",
    "Togo": "https://flagcdn.com/w320/tg.png",
    "Malawi": "https://flagcdn.com/w320/mw.png",
    "Ethiopia": "https://flagcdn.com/w320/et.png",
    "Rwanda": "https://flagcdn.com/w320/rw.png",
    "Gabon": "https://flagcdn.com/w320/ga.png",
    "Senegal": "https://flagcdn.com/w320/sn.png",
    "Afghanistan": "https://flagcdn.com/w320/af.png",
    "Gambia": "https://flagcdn.com/w320/gm.png",
    "Liberia": "https://flagcdn.com/w320/lr.png",
    "United Republic of Tanzania": "https://flagcdn.com/w320/tz.png",
    "Swaziland": "https://flagcdn.com/w320/sz.png",
    "Congo": "https://flagcdn.com/w320/cg.png",
    "Papua New Guinea": "https://flagcdn.com/w320/pg.png",
    "Ghana": "https://flagcdn.com/w320/gh.png"
}

# 5. Colores principales
flag_colors = {
    "Sierra Leone":                     "#1EB53A",
    "Central African Republic":         "#003082",
    "Lesotho":                          "#1E90FF",
    "Nigeria":                          "#008751",
    "Chad":                             "#002664",
    "Cote d'Ivoire":                    "#F77F00",
    "Guinea-Bissau":                    "#CE1126",
    "Somalia":                          "#4189DD",
    "South Sudan":                      "#0F47AF",
    "Zimbabwe":                         "#006400",
    "Burundi":                          "#1EB53A",
    "Mali":                             "#14B53A",
    "Cameroon":                         "#007A5E",
    "Mozambique":                       "#D21034",
    "Democratic Republic of the Congo": "#007FFF",
    "Equatorial Guinea":                "#3E9A00",
    "Guinea":                           "#FCD116",
    "Benin":                            "#008751",
    "Burkina Faso":                     "#EF2B2D",
    "Uganda":                           "#FCDC04",
    "Zambia":                           "#198A00",
    "Niger":                            "#E15307",
    "Angola":                           "#CE1126",
    "Togo":                             "#006A4E",
    "Malawi":                           "#000000",
    "Ethiopia":                         "#078930",
    "Rwanda":                           "#00A1DE",
    "Gabon":                            "#009E60",
    "Senegal":                          "#00853F",
    "Afghanistan":                      "#000000",
    "Gambia":                           "#CE1126",
    "Liberia":                          "#002868",
    "United Republic of Tanzania":      "#1EB53A",
    "Swaziland":                        "#3E5EB9",
    "Congo":                            "#009543",
    "Papua New Guinea":                 "#000000",
    "Ghana":                            "#CE1126"
}

# 6. Función bandera
def get_flag(country):
    try:
        url = flag_urls[country]
        response = requests.get(url, timeout=5)
        img = Image.open(BytesIO(response.content)).convert("RGB")
        img = img.resize((60, 38), Image.LANCZOS)
        return np.array(img)
    except:
        return None

# 7. Pre-cargar banderas
print("Descargando banderas...")
flag_thumbs = {c: get_flag(c) for c in countries}
print("Listo!")

# 8. Figura
fig, ax = plt.subplots(figsize=(16, 12))
plt.subplots_adjust(right=0.82)

for i, country in enumerate(countries):
    color = flag_colors.get(country, "#888888")
    thumb = flag_thumbs[country]

    ax.barh(i, life_exp[i], color=color, edgecolor="black", linewidth=0.8, height=0.7)

    ax.text(life_exp[i] + 0.2, i, f"{life_exp[i]:.1f}",
            va='center', ha='left', fontsize=9)

    if thumb is not None:
        im = OffsetImage(thumb, zoom=0.6)
        ab = AnnotationBbox(
            im,
            xy=(1, i),
            xycoords=('axes fraction', 'data'),
            box_alignment=(-0.2, 0.5),
            frameon=True,
            bboxprops=dict(edgecolor="gray", linewidth=0.6)
        )
        ax.add_artist(ab)

# 9. Estilo final
ax.set_yticks(range(len(countries)))
ax.set_yticklabels(countries, fontsize=9)
ax.set_xlabel("Expectativa de vida (años)", fontsize=11)
ax.set_title("30 países con menor expectativa de vida (2015)", fontsize=13, fontweight='bold')
ax.invert_yaxis()
ax.set_xlim(0, max(life_exp) + 5)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.show()

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

cols = [
    "Life expectancy",
    "Schooling",
    "GDP",
    "Adult Mortality",
    "infant deaths"
]

df1[cols] = scaler.fit_transform(df1[cols])

score = (
    df1["Life expectancy"] * 0.4
    + df1["Schooling"] * 0.1
    + df1["GDP"] * 0.3
    - df1["Adult Mortality"] * 0.1
    - df1["infant deaths"] * 0.1
)

df1["Score"] = score

# Filtrar año 2015
df1_2015 = df1[df1["Year"] == 2015]

# Top países según Score
top_paises = (
    df1_2015.groupby("Country")["Score"]
    .mean()
    .sort_values(ascending=False)
    .head(10)
)

print(top_paises)

# Filtrar año 2015
df1_2015 = df1[df1["Year"] == 2015]

# 10 países con menor Score
bottom_paises = (
    df1_2015.groupby("Country")["Score"]
    .mean()
    .sort_values(ascending=True)
    .head(10)
)

print(bottom_paises)

from sklearn.preprocessing import MinMaxScaler

cols = [
    "Hepatitis B",
    "Measles",
    "Diphtheria",
    "HIV/AIDS",
    "Polio"
]

scaler = MinMaxScaler()
df1[cols] = scaler.fit_transform(df1[cols])

score = (
    (1 - df1["Hepatitis B"]) * 0.2
    + df1["Measles"] * 0.2
    + (1 - df1["Diphtheria"]) * 0.2
    + df1["HIV/AIDS"] * 0.3
    + (1 - df1["Polio"]) * 0.1
)

df1["Enfermedades Score"] = (
    (1 - df1["Hepatitis B"]) * 0.2
    + df1["Measles"] * 0.2
    + (1 - df1["Diphtheria"]) * 0.2
    + df1["HIV/AIDS"] * 0.3
    + (1 - df1["Polio"]) * 0.1
)

# Columnas a revisar para valores cero
cols_to_filter = [
    "Hepatitis B",
    "Measles",
    "Diphtheria",
    "HIV/AIDS",
    "Polio"
]

# Filtrar df1 para eliminar filas donde cualquiera de las columnas seleccionadas es cero
df1 = df1[~(df1[cols_to_filter] == 0).any(axis=1)]

print(f"DataFrame df1 después de eliminar filas con ceros: {df1.shape[0]} filas")

# Volver a crear df1_2015 con los datos ya limpios
df1_2015 = df1[df1['Year'] == 2015]

# Columnas a mostrar
cols_to_display = ['Country', 'Hepatitis B', 'Measles', 'Diphtheria', 'HIV/AIDS', 'Polio', 'Enfermedades Score']

display(df1_2015[cols_to_display].sort_values("Enfermedades Score", ascending=False).head(10))

df1_2015 = df1[df1["Year"] == 2015]
df1.sort_values("Enfermedades Score", ascending=True).head(10)

df1_2015 = df1[df1['Year'] == 2015]
display(df1_2015.sort_values("Enfermedades Score", ascending=False).head(10))

cols_to_display = ['Country', 'Hepatitis B', 'Measles', 'Diphtheria', 'HIV/AIDS', 'Polio', 'Enfermedades Score']
display(df1_2015[cols_to_display].sort_values("Enfermedades Score", ascending=False).head(10))
df1 = df1[~(df1[cols] == 0).any(axis=1)]

cols_to_display = ['Country', 'Hepatitis B', 'Measles', 'Diphtheria', 'HIV/AIDS', 'Polio', 'Enfermedades Score']
display(df1_2015[cols_to_display].sort_values("Enfermedades Score", ascending=True).head(10))
df1 = df1[~(df1[cols] == 0).any(axis=1)]

# Mostrar filas que tengan al menos un 0 en las columnas seleccionadas

cols = [
    "Hepatitis B",
    "Measles",
    "Diphtheria",
    "HIV/AIDS",
    "Polio"
]

# Filas con algún 0
rows_with_zero = df1[(df1[cols] == 0).any(axis=1)]

# Agrupar por país y mostrar columnas con 0
for country, group in rows_with_zero.groupby("Country"):
    print(f"\n{country}")

    for index, row in group.iterrows():
        zero_cols = [col for col in cols if row[col] == 0]
        print("Columnas con 0:", zero_cols)

# =========================
# 1. IMPORTAR LIBRERÍAS
# =========================

import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# =========================
# 2. SELECCIONAR COLUMNAS
# =========================

cols = [
    "Hepatitis B",
    "Measles",
    "Diphtheria",
    "HIV/AIDS",
    "Polio"
]

# =========================
# 3. ELIMINAR NULOS
# =========================

df1 = df1.dropna(subset=cols)

# =========================
# 4. ELIMINAR SOLO CEROS
# EN VACUNACIÓN
# =========================

df1 = df1[
    (df1["Hepatitis B"] != 0) &
    (df1["Diphtheria"] != 0) &
    (df1["Polio"] != 0)
]

# =========================
# 5. NORMALIZAR VARIABLES
# =========================

scaler = MinMaxScaler()

df1[cols] = scaler.fit_transform(df1[cols])

# =========================
# 6. CREAR SCORE
# =========================

df1["Enfermedades Score"] = (
    (1 - df1["Hepatitis B"]) * 0.25
    + df1["Measles"] * 0.15
    + (1 - df1["Diphtheria"]) * 0.25
    + df1["HIV/AIDS"] * 0.25
    + (1 - df1["Polio"]) * 0.10
)

# =========================
# 7. ORDENAR RESULTADOS
# =========================

df1 = df1.sort_values(
    by="Enfermedades Score",
    ascending=False
)

# =========================
# 8. MOSTRAR RESULTADOS
# =========================

print(df1[
    [
        "Country",
        "Hepatitis B",
        "Measles",
        "Diphtheria",
        "HIV/AIDS",
        "Polio",
        "Enfermedades Score"
    ]
].head(20))

from google.colab import files
uploaded = files.upload()

import pandas as pd
df2 = pd.read_excel("2015.year.xlsx")

df2.head()

pd.merge(df1, df2, on='Country', how='inner')

pd.merge(df1, df2, on=['Country', 'Year'], how='inner')

pd.merge(df1, df2, on=['Country', 'Year'], how='right')

# ============================================
# GRÁFICO GDP HISTÓRICO + FORECAST 2025
# ============================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# ============================================
# 1. CARGAR DATASETS
# ============================================

df1 = pd.read_csv("Life Expectancy Data.csv")
df2 = pd.read_excel("2015.year.xlsx")

# ============================================
# 2. LIMPIEZA
# ============================================

df1['GDP'] = pd.to_numeric(df1['GDP'], errors='coerce')

df1 = df1.dropna(subset=['GDP', 'Year'])

# ============================================
# 3. GDP PROMEDIO POR AÑO
# ============================================

df1_gdp_evolution = (
    df1.groupby('Year')['GDP']
    .mean()
    .reset_index()
)

# ============================================
# 4. TOMAR GDP DEL DF2
# ============================================

possible_gdp_cols = [
    col for col in df2.columns
    if 'gdp' in col.lower()
]

gdp_col_df2 = possible_gdp_cols[0]

df2[gdp_col_df2] = pd.to_numeric(
    df2[gdp_col_df2],
    errors='coerce'
)

df2_gdp_2015 = df2[gdp_col_df2].mean()

# ============================================
# 5. SUMAR EL GDP DEL DF2 AL 2015
# ============================================

df1_gdp_evolution = df1_gdp_evolution.copy()

mask_2015 = df1_gdp_evolution['Year'] == 2015

df1_gdp_evolution.loc[mask_2015, 'GDP'] = (
    df1_gdp_evolution.loc[mask_2015, 'GDP']
    + df2_gdp_2015
)

# ============================================
# 6. MODELO DE REGRESIÓN
# ============================================

X = df1_gdp_evolution[['Year']]
y = df1_gdp_evolution['GDP']

model = LinearRegression()
model.fit(X, y)

# ============================================
# 7. PREDICCIÓN HASTA 2025
# ============================================

future_years = np.arange(
    df1_gdp_evolution['Year'].max() + 1,
    2026
).reshape(-1, 1)

predicted_gdp = model.predict(future_years)

predictions_df = pd.DataFrame({
    'Year': future_years.flatten(),
    'GDP': predicted_gdp
})

# ============================================
# 8. UNIR ÚLTIMO PUNTO HISTÓRICO
# ============================================

last_historical = df1_gdp_evolution.iloc[-1:]

forecast_plot = pd.concat([
    last_historical,
    predictions_df
])

# ============================================
# 9. GRÁFICO
# ============================================

plt.figure(figsize=(14,8))

# Fondo negro
plt.style.use('dark_background')

# HISTÓRICO
plt.plot(
    df1_gdp_evolution['Year'],
    df1_gdp_evolution['GDP'],
    marker='o',
    linewidth=3,
    color='#6EA8FE',
    label='GDP Histórico'
)

# FORECAST
plt.plot(
    forecast_plot['Year'],
    forecast_plot['GDP'],
    marker='o',
    linestyle='--',
    linewidth=3,
    color='#FFD43B',
    label='Forecast GDP 2025'
)

# ============================================
# ETIQUETAS DE LOS PUNTOS
# ============================================

for x, y in zip(
    df1_gdp_evolution['Year'],
    df1_gdp_evolution['GDP']
):
    plt.text(
        x,
        y,
        f'{y:.0f}',
        fontsize=10,
        color='white',
        ha='center',
        va='bottom'
    )

for x, y in zip(
    predictions_df['Year'],
    predictions_df['GDP']
):
    plt.text(
        x,
        y,
        f'{y:.0f}',
        fontsize=10,
        color='#FFD43B',
        ha='center',
        va='bottom'
    )

# ============================================
# TÍTULOS Y EJES
# ============================================

plt.title(
    'Evolución Histórica + Forecast del GDP',
    fontsize=22,
    weight='bold'
)

# EJE X
plt.xlabel(
    'Año',
    fontsize=15,
    weight='bold'
)

# EJE Y
plt.ylabel(
    'GDP',
    fontsize=15,
    weight='bold'
)

# ============================================
# GRID
# ============================================

plt.grid(
    True,
    linestyle='--',
    alpha=0.3
)

# ============================================
# TICKS
# ============================================

plt.xticks(
    list(df1_gdp_evolution['Year']) +
    list(predictions_df['Year']),
    rotation=45
)

# ============================================
# LEYENDA
# ============================================

plt.legend(fontsize=13)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Filtrar df_merged para el año 2015, ya que 'Happiness_Score' solo está disponible para ese año
df_2015_analysis = df_merged[df_merged['Year'] == 2015].dropna(subset=['Life expectancy', 'Happiness_Score'])

# Crear el gráfico de dispersión
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Happiness_Score', y='Life expectancy', data=df_2015_analysis, hue='Region', size='GDP', sizes=(50, 500), alpha=0.7)
sns.regplot(x='Happiness_Score', y='Life expectancy', data=df_2015_analysis, scatter=False, color='gray', line_kws={'linestyle': '--'})

plt.title('Expectativa de Vida vs. Puntuación de Felicidad en 2015')
plt.xlabel('Puntuación de Felicidad (Happiness Score)')
plt.ylabel('Expectativa de Vida')
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.)
plt.tight_layout()
plt.show()

import plotly.express as px

# Filtrar df_merged para el año 2015, ya que 'Happiness_Score' solo está disponible para ese año
df_2015_analysis = df_merged[df_merged['Year'] == 2015].dropna(subset=['Life expectancy', 'Happiness_Score', 'Region', 'GDP'])

fig = px.scatter(
    df_2015_analysis,
    x='Happiness_Score',
    y='Life expectancy',
    color='Region',
    size='GDP',
    hover_name='Country',
    hover_data=['Adult Mortality', 'Schooling', 'HIV/AIDS', 'Trust_Government_Corruption'],
    title='Expectativa de Vida vs. Puntuación de Felicidad en 2015 (Interactivo)',
    labels={
        'Happiness_Score': 'Puntuación de Felicidad',
        'Life expectancy': 'Expectativa de Vida',
        'GDP': 'PIB (en miles de USD)',
        'Adult Mortality': 'Mortalidad Adultos',
        'Schooling': 'Años de Escolaridad',
        'HIV/AIDS': 'Prevalencia HIV/SIDA',
        'Trust_Government_Corruption': 'Confianza en Gobierno (Corrupción)'
    }
)

fig.update_layout(showlegend=True) # Ensure legend is visible
fig.show()

# ============================================
# COMPARAR PREDICCIÓN VS GDP REAL 2025
# ============================================

# GDP predicho para 2025
gdp_pred_2025 = predictions_df.loc[
    predictions_df['Year'] == 2025,
    'GDP'
].values[0]

# ============================================
# INGRESA EL GDP REAL 2025
# (puedes buscarlo en World Bank, IMF, etc.)
# ============================================

gdp_real_2025 = 14500   # EJEMPLO

# ============================================
# ERROR ABSOLUTO
# ============================================

absolute_error = abs(gdp_real_2025 - gdp_pred_2025)

# ============================================
# ERROR PORCENTUAL
# ============================================

percentage_error = (
    absolute_error / gdp_real_2025
) * 100

# ============================================
# ACCURACY
# ============================================

accuracy = 100 - percentage_error

# ============================================
# RESULTADOS
# ============================================

print("\n========= VALIDACIÓN DEL FORECAST =========")

print(f"GDP Predicho 2025 : {gdp_pred_2025:.2f}")
print(f"GDP Real 2025     : {gdp_real_2025:.2f}")

print(f"\nError absoluto    : {absolute_error:.2f}")
print(f"Error porcentual  : {percentage_error:.2f}%")

print(f"\nAccuracy del modelo: {accuracy:.2f}%")

import matplotlib.pyplot as plt
import seaborn as sns

# Ensure df_merged is up-to-date and columns are renamed consistently
# This assumes df1 and df2 are already loaded and preprocessed as needed

# Strip whitespace from column names in both df1 and df2 for robust merging
df1.columns = df1.columns.str.strip()
df2.columns = df2.columns.str.strip()

df_merged = pd.merge(df1, df2, on=['Country', 'Year'], how='inner')

df_merged = df_merged.rename(columns={
    'Happiness Score': 'Happiness_Score',
    'Trust (Government Corruption)': 'Trust_Government_Corruption',
    'Economy (GDP per Capita)': 'Economy_GDP_per_Capita'
})

# Filter for the year 2015 and drop rows with missing values in the relevant columns
df_2015_economy_analysis = df_merged[df_merged['Year'] == 2015].dropna(subset=['Life expectancy', 'Economy_GDP_per_Capita', 'Region', 'Trust_Government_Corruption'])

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Economy_GDP_per_Capita', y='Life expectancy', data=df_2015_economy_analysis, hue='Region', size='Trust_Government_Corruption', sizes=(50, 500), alpha=0.7)
sns.regplot(x='Economy_GDP_per_Capita', y='Life expectancy', data=df_2015_economy_analysis, scatter=False, color='gray', line_kws={'linestyle': '--'})

plt.title('Life Expectancy vs. Economy (GDP per Capita) in 2015')
plt.xlabel('Economy (GDP per Capita)')
plt.ylabel('Life expectancy')
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.)
plt.tight_layout()
plt.show()

import plotly.express as px

# Merge df1 and df2 on 'Country' and 'Year'
df_merged = pd.merge(df1, df2, on=['Country', 'Year'], how='inner')

# Rename columns to match the plotting function's expectations
df_merged = df_merged.rename(columns={
    'Happiness Score': 'Happiness_Score',
    'Trust (Government Corruption)': 'Trust_Government_Corruption'
})

# Filter df_merged for the year 2015, as 'Happiness_Score' is only available for that year
df_2015_analysis = df_merged[df_merged['Year'] == 2015].dropna(subset=['Life expectancy', 'Happiness_Score', 'Region', 'GDP'])

fig = px.scatter(
    df_2015_analysis,
    x='Happiness_Score',
    y='Life expectancy',
    color='Region',
    size='GDP',
    hover_name='Country',
    hover_data=['Adult Mortality', 'Schooling', 'HIV/AIDS', 'Trust_Government_Corruption'],
    title='Expectativa de Vida vs. Puntuación de Felicidad en 2015 (Interactivo)',
    labels={
        'Happiness_Score': 'Puntuación de Felicidad',
        'Life expectancy': 'Expectativa de Vida',
        'GDP': 'PIB (en miles de USD)',
        'Adult Mortality': 'Mortalidad Adultos',
        'Schooling': 'Años de Escolaridad',
        'HIV/AIDS': 'Prevalencia HIV/SIDA',
        'Trust_Government_Corruption': 'Confianza en Gobierno (Corrupción)'
    }
)

fig.update_layout(showlegend=True) # Ensure legend is visible
fig.show()

from google.colab import files
files.download('grafico.html')
fig.write_html("grafico.html", full_html=True)

import matplotlib.pyplot as plt

# 1. Filtramos los datos específicos de Argentina y los ordenamos cronológicamente
df_arg = df1[df1['Country'] == 'Argentina'].sort_values('Year')

# 2. Configuramos el tamaño del gráfico
fig, ax1 = plt.subplots(figsize=(12, 6))

# 3. EJE Y IZQUIERDO: Esperanza de Vida
color_vida = '#1f77b4' # Azul
ax1.set_xlabel('Año', fontweight='bold', fontsize=12)
ax1.set_ylabel('Esperanza de Vida (Años)', color=color_vida, fontweight='bold', fontsize=12)
linea1 = ax1.plot(df_arg['Year'], df_arg['Life expectancy'], color=color_vida, marker='o', linewidth=2.5, label='Esperanza de Vida')
ax1.tick_params(axis='y', labelcolor=color_vida)

# 4. EJE Y DERECHO: PBI (Aquí está la magia del twinx)
ax2 = ax1.twinx()
color_pbi = '#2ca02c' # Verde
ax2.set_ylabel('PBI (USD)', color=color_pbi, fontweight='bold', fontsize=12)
linea2 = ax2.plot(df_arg['Year'], df_arg['GDP'], color=color_pbi, marker='s', linestyle='--', linewidth=2.5, label='PBI')
ax2.tick_params(axis='y', labelcolor=color_pbi)

# 5. Estética y Leyendas
plt.title('Evolución de la Esperanza de Vida vs. PBI en Argentina', fontsize=16, fontweight='bold', pad=20)
ax1.grid(True, linestyle='--', alpha=0.5)

# Unimos las etiquetas de ambos ejes para una sola leyenda
lineas = linea1 + linea2
etiquetas = [l.get_label() for l in lineas]
ax1.legend(lineas, etiquetas, loc='upper left', frameon=True, shadow=True)

# Ajustamos el espaciado para que no se corten los números
fig.tight_layout()
plt.show()

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from google.colab import files

# Ensure df1 is loaded and cleaned within this cell for self-containment
df1 = pd.read_csv("Life Expectancy Data.csv")
df1.columns = df1.columns.str.strip()

# 1. Filtramos los datos de Argentina y los ordenamos por año
df_arg = df1[df1['Country'] == 'Argentina'].sort_values('Year')

# 2. Creamos el lienzo indicando explícitamente que tendrá un eje Y secundario
fig = make_subplots(specs=[[{"secondary_y": True}]])

# 3. EJE Y IZQUIERDO: Esperanza de Vida (Línea Azul con círculos)
color_vida = '#1f77b4' # Azul corporativo
fig.add_trace(
    go.Scatter(
        x=df_arg['Year'],
        y=df_arg['Life expectancy'],
        name="Esperanza de Vida",
        mode='lines+markers',
        line=dict(color=color_vida, width=3),
        marker=dict(symbol='circle', size=8)
    ),
    secondary_y=False,
)

# 4. EJE Y DERECHO: Gasto en Salud Pública (Línea Roja punteada con triángulos)
color_salud = '#d62728' # Rojo para contrastar el gasto
fig.add_trace(
    go.Scatter(
        x=df_arg['Year'],
        y=df_arg['Total expenditure'],
        name="Inversión en Salud",
        mode='lines+markers',
        line=dict(color=color_salud, width=3, dash='dash'), # Línea punteada
        marker=dict(symbol='triangle-up', size=8)
    ),
    secondary_y=True,
)

# 5. Título, Estética y la magia de la interactividad unificada
fig.update_layout(
    title_text="Evolución: Esperanza de Vida vs. Inversión en Salud Pública (Argentina)",
    title_font=dict(size=22, family="Arial", color="black"), # Agrandar título
    title_x=0.5, # Centrar el título
    plot_bgcolor='white',
    # Al pasar el cursor, muestra los datos de ambas variables en simultáneo
    hovermode="x unified",
    legend=dict(x=0.01, y=0.99, bgcolor='rgba(255, 255, 255, 0.8)', font=dict(size=16, color="black")) # Agrandar leyenda
)

# Formateamos las etiquetas y las cuadrículas de fondo para el estándar del reporte
fig.update_yaxes(
    title_text="<b>Esperanza de Vida (Años)</b>",
    color=color_vida,
    secondary_y=False,
    showgrid=True,
    gridcolor='lightgrey',
    gridwidth=1,
    griddash='dash',
    title_font=dict(size=18, color=color_vida), # Agrandar título eje Y
    tickfont=dict(size=14, color=color_vida)   # Agrandar ticks eje Y
)
fig.update_yaxes(
    title_text="<b>Gasto en Salud (% del gasto total del Gob.)</b>",
    color=color_salud,
    secondary_y=True,
    showgrid=False,
    title_font=dict(size=18, color=color_salud), # Agrandar título eje Y secundario
    tickfont=dict(size=14, color=color_salud)   # Agrandar ticks eje Y secundario
)
fig.update_xaxes(
    title_text="<b>Año</b>",
    showgrid=True,
    gridcolor='lightgrey',
    title_font=dict(size=18, color="black"), # Agrandar título eje X
    tickfont=dict(size=14, color="black")   # Agrandar ticks eje X
)

fig.show()

# 2. Guardar el gráfico interactivo en formato HTML
# ATENCIÓN: ¡Cambia el nombre aquí para que no se pisen entre ellos!
nombre_archivo = "mi_nuevo_grafico_salud.html"
fig.write_html(nombre_archivo, full_html=True)

# 3. Descargar el archivo automáticamente a tu compu
files.download(nombre_archivo)

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from google.colab import files

# Ensure df1 is available and its columns are clean
# (Assuming df1 is loaded in previous cells, if not, add: df1 = pd.read_csv("Life Expectancy Data.csv"); df1.columns = df1.columns.str.strip())

# 1. Filtramos los datos de Argentina y los ordenamos por año
df_arg = df1[df1['Country'] == 'Argentina'].sort_values('Year')

# 2. Creamos el lienzo indicando explícitamente que tendrá un eje Y secundario
fig = make_subplots(specs=[[{"secondary_y": True}]])

# 3. EJE Y IZQUIERDO: Esperanza de Vida (Línea Azul con círculos)
color_vida = '#1f77b4' # Azul corporativo
fig.add_trace(
    go.Scatter(
        x=df_arg['Year'],
        y=df_arg['Life expectancy'],
        name="Esperanza de Vida",
        mode='lines+markers',
        line=dict(color=color_vida, width=3),
        marker=dict(symbol='circle', size=8)
    ),
    secondary_y=False,
)

# 4. EJE Y DERECHO: Escolaridad (Línea Púrpura guion-punto con diamantes)
color_edu = '#9467bd' # Púrpura para representar la educación
fig.add_trace(
    go.Scatter(
        x=df_arg['Year'],
        y=df_arg['Schooling'],
        name="Escolaridad (Años promedio)",
        mode='lines+markers',
        line=dict(color=color_edu, width=3, dash='dashdot'), # Línea guion-punto
        marker=dict(symbol='diamond', size=8)
    ),
    secondary_y=True,
)

# 5. Título, Estética y la magia de la interactividad unificada
fig.update_layout(
    title_text="Evolución: Esperanza de Vida vs. Nivel de Escolaridad (Argentina)",
    title_font=dict(size=22, family="Arial", color="black"), # Agrandar título
    title_x=0.5, # Centrar el título
    plot_bgcolor='white',
    # Al pasar el cursor, muestra los datos de ambas variables en simultáneo
    hovermode="x unified",
    legend=dict(x=0.01, y=0.99, bgcolor='rgba(255, 255, 255, 0.8)', font=dict(size=16, color="black")) # Agrandar leyenda
)

# Formateamos las etiquetas y las cuadrículas de fondo para el estándar del reporte
fig.update_yaxes(
    title_text="<b>Esperanza de Vida (Años)</b>",
    color=color_vida,
    secondary_y=False,
    showgrid=True,
    gridcolor='lightgrey',
    gridwidth=1,
    griddash='dash',
    title_font=dict(size=18, color=color_vida), # Agrandar título eje Y
    tickfont=dict(size=14, color=color_vida)   # Agrandar ticks eje Y
)
fig.update_yaxes(
    title_text="<b>Escolaridad (Años promedio)</b>",
    color=color_edu,
    secondary_y=True,
    showgrid=False,
    title_font=dict(size=18, color=color_edu), # Agrandar título eje Y secundario
    tickfont=dict(size=14, color=color_edu)   # Agrandar ticks eje Y secundario
)
fig.update_xaxes(
    title_text="<b>Año</b>",
    showgrid=True,
    gridcolor='lightgrey',
    title_font=dict(size=18, color="black"), # Agrandar título eje X
    tickfont=dict(size=14, color="black")   # Agrandar ticks eje X
)

fig.show()

# 2. Guardar el gráfico interactivo en formato HTML
# ATENCIÓN: ¡Cambia el nombre aquí para que no se pisen entre ellos!
nombre_archivo = "mi_nuevo_grafico_escolaridad.html"
fig.write_html(nombre_archivo, full_html=True)

# 3. Descargar el archivo automáticamente a tu compu
files.download(nombre_archivo)

# 1. Eliminamos espacios en blanco invisibles al principio o al final de los nombres
df1['Country'] = df1['Country'].str.strip()

# 2. Creamos un diccionario de traducción para los casos conflictivos de la OMS y el Happiness Report
diccionario_paises = {
    'EEUU': 'United States',
    'Estados Unidos': 'United States',
    'United States of America': 'United States',
    'Reino Unido': 'United Kingdom',
    'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom',
    'Russian Federation': 'Russia',
    'Bolivia (Plurinational State of)': 'Bolivia',
    'Venezuela (Bolivarian Republic of)': 'Venezuela',
    'Iran (Islamic Republic of)': 'Iran',
    'Viet Nam': 'Vietnam',
    'Republic of Korea': 'South Korea'
}

# 3. Aplicamos el reemplazo en la columna 'Country'
df1['Country'] = df1['Country'].replace(diccionario_paises)

import plotly.express as px
import pandas as pd

# 1. Load dataframes (ensure they are available in this cell's scope)
df1 = pd.read_csv("Life Expectancy Data.csv")
df2 = pd.read_excel("2015.year.xlsx")

# Ensure df1 and df2 columns are stripped of whitespace before merging
df1.columns = df1.columns.str.strip()
df2.columns = df2.columns.str.strip()

# Merge df1 and df2 on 'Country' and 'Year'
df_merged = pd.merge(df1, df2, on=['Country', 'Year'], how='inner')

# Rename columns to match the plotting function's expectations
df_merged = df_merged.rename(columns={
    'Happiness Score': 'Happiness_Score',
    'Trust (Government Corruption)': 'Trust_Government_Corruption',
    'Economy (GDP per Capita)': 'Economy_GDP_per_Capita'
})

# Filter df_merged for the year 2015, as 'Happiness_Score' is only available for that year
df_2015_analysis = df_merged[df_merged['Year'] == 2015].dropna(subset=['Life expectancy', 'Happiness_Score', 'Region', 'GDP'])

fig = px.choropleth(
    df_2015_analysis,
    locations="Country",
    locationmode="country names",
    color="Happiness_Score",
    hover_name="Country",
    color_continuous_scale="Viridis",
    title="Mapa de Calor Global: Índice de Felicidad (2015)",
    labels={'Happiness_Score': 'Puntaje de Felicidad'}
)

# Ajustes de estética para que se vea como un reporte de consultoría
fig.update_layout(
    geo=dict(
        showframe=False,
        showcoastlines=True,
        projection_type='equirectangular'
    ),
    title_font_size=20,
    title_x=0.5
)

fig.show()

import plotly.express as px

# Asumiendo que tu dataframe ya está filtrado para el año 2015 y se llama 'df'
# Ojo: Asegurate de escribir el nombre de la columna exactamente como está en tu dataset
# (en los anteriores tenía un espacio al final: 'Life expectancy ')

fig = px.choropleth(
    df_2015_analysis,
    locations="Country",
    locationmode="country names",
    color="Life expectancy",          # Variable de la OMS, corregido sin espacio al final
    hover_name="Country",
    color_continuous_scale="Plasma",  # Paleta cálida/fría para diferenciar del otro mapa
    title="Mapa de Calor Global: Esperanza de Vida al Nacer (2015)",
    labels={'Life expectancy': 'Esperanza de Vida (Años)'} # Corregido sin espacio al final
)

# Ajustes de estética para mantener el estándar de consultoría
fig.update_layout(
    geo=dict(
        showframe=False,
        showcoastlines=True,
        projection_type='equirectangular'
    ),
    title_font_size=20,
    title_x=0.5
)

fig.show()

ffrom google.colab import files
files.download('grafico.html')
fig.write_html("grafico.html", full_html=True)

# 1. Eliminamos espacios en blanco invisibles al principio o al final de los nombres
df['Country'] = df['Country'].str.strip()

# 2. Creamos un diccionario de traducción para los casos conflictivos de la OMS y el Happiness Report
diccionario_paises = {
    'EEUU': 'United States',
    'Estados Unidos': 'United States',
    'United States of America': 'United States',
    'Reino Unido': 'United Kingdom',
    'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom',
    'Russian Federation': 'Russia',
    'Bolivia (Plurinational State of)': 'Bolivia',
    'Venezuela (Bolivarian Republic of)': 'Venezuela',
    'Iran (Islamic Republic of)': 'Iran',
    'Viet Nam': 'Vietnam',
    'Republic of Korea': 'South Korea'
}

# 3. Aplicamos el reemplazo en la columna 'Country'
df['Country'] = df['Country'].replace(diccionario_paises)

import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pandas as pd

# Load and preprocess df1 to ensure it's defined and clean
df1 = pd.read_csv("Life Expectancy Data.csv")
df1 = df1.dropna(subset=['Life expectancy ']) # Keep this with space for initial dropna
df1 = df1[df1['Life expectancy '] != 0] # Keep this with space for initial filter
df1.columns = df1.columns.str.strip() # Strip all columns here

# 1. Creamos el lienzo indicando explícitamente que tendrá un eje Y secundario
fig = make_subplots(specs=[[{"secondary_y": True}]])

# Filter for Argentina data and sort by year
df_argentina = df1[df1['Country'] == 'Argentina'].sort_values('Year')

# 2. Agregamos la primera variable: El KPI de Gasto en Salud (Eje Y principal - Izquierda)
# Usamos un gráfico de barras para el volumen del presupuesto
fig.add_trace(
    go.Bar(
        x=df_argentina['Year'],
        y=df_argentina['Total expenditure'],
        name="Gasto en Salud (% PBI)",
        marker_color='#636EFA'
    ),
    secondary_y=False,
)

# 3. Agregamos la segunda variable: La Esperanza de Vida (Eje Y secundario - Derecha)
# Usamos una línea con marcadores para ver la evolución y la tendencia
fig.add_trace(
    go.Scatter(
        x=df_argentina['Year'],
        y=df_argentina['Life expectancy'], # Corrected column name
        name="Esperanza de Vida (Años)",
        mode='lines+markers',
        marker_color='#EF553B'
    ),
    secondary_y=True,
)

# 4. Ajustes visuales de nivel profesional
fig.update_layout(
    title_text="Eficiencia Sanitaria y Longevidad en Argentina",
    title_x=0.5,
    # ¡Esta es la configuración mágica!
    # Agrupa los datos en una sola caja al pasar el mouse por un año específico
    hovermode="x unified",
    plot_bgcolor='white'
)

# Ajustamos las etiquetas de cada eje
fig.update_yaxes(title_text="<b>Gasto en Salud</b> (%)", secondary_y=False)
fig.update_yaxes(title_text="<b>Esperanza de Vida</b> (Años)", secondary_y=True)

fig.show()

import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pandas as pd # Import pandas here

# Ensure df1 is loaded and cleaned within this cell for self-containment
df1 = pd.read_csv("Life Expectancy Data.csv")
df1.columns = df1.columns.str.strip()

# 1. Filtramos los datos de Argentina y los ordenamos por año
df_arg = df1[df1['Country'] == 'Argentina'].sort_values('Year')

# 2. Creamos el lienzo indicando explícitamente que tendrá un eje Y secundario
fig = make_subplots(specs=[[{"secondary_y": True}]])

# 3. EJE Y IZQUIERDO: Esperanza de Vida (Línea Azul)
fig.add_trace(
    go.Scatter(
        x=df_arg['Year'],
        y=df_arg['Life expectancy'], # Chequeá si tu columna tiene un espacio al final
        name="Esperanza de Vida",
        mode='lines+markers',
        line=dict(color='#1f77b4', width=3),
        marker=dict(size=8)
    ),
    secondary_y=False,
)

# 4. EJE Y DERECHO: PBI (Línea Verde)
fig.add_trace(
    go.Scatter(
        x=df_arg['Year'],
        y=df_arg['GDP'],
        name="PBI (USD)",
        mode='lines+markers',
        line=dict(color='#2ca02c', width=3, dash='dash'), # Línea punteada como tenías
        marker=dict(symbol='square', size=8)
    ),
    secondary_y=True,
)

# 5. Estética, Leyendas y la magia de la interactividad
fig.update_layout(
    title_text="Evolución de la Esperanza de Vida vs. PBI en Argentina",
    title_font=dict(size=20),
    title_x=0.5, # Centra el título
    plot_bgcolor='white',
    # ESTO ES LO QUE LO HACE DINÁMICO:
    # Muestra los datos de ambas líneas en un solo cuadro al pasar el mouse
    hovermode="x unified",
    legend=dict(x=0.01, y=0.99, bgcolor='rgba(255, 255, 255, 0.8)')
)

# Ajustamos los títulos de cada eje para que coincidan con tu diseño original
fig.update_yaxes(title_text="<b>Esperanza de Vida (Años)</b>", color='#1f77b4', secondary_y=False, showgrid=True, gridcolor='lightgrey', gridwidth=1, griddash='dash')
fig.update_yaxes(title_text="<b>PBI (USD)</b>", color='#2ca02c', secondary_y=True, showgrid=False)
fig.update_xaxes(title_text="<b>Año</b>", showgrid=True, gridcolor='lightgrey')

# Forzar tamaños grandes para la presentación
fig.update_layout(
    title_font=dict(size=22),          # Tamaño del título principal
    legend=dict(font=dict(size=16)),   # Tamaño de la leyenda
    xaxis=dict(title_font=dict(size=18), tickfont=dict(size=14)), # Tamaño del eje X
    yaxis=dict(title_font=dict(size=18), tickfont=dict(size=14)), # Tamaño del eje Y principal
)

# Si tenés un eje Y secundario (como en el de Argentina), agregá esta línea también:
fig.update_yaxes(title_font=dict(size=18), tickfont=dict(size=14), secondary_y=True)

fig.show()

# 1. Importás la herramienta de descargas de Colab
from google.colab import files

# 2. Guardás el gráfico como un archivo HTML en la memoria de Colab
fig.write_html("Esperanza vs pbi argentina.html", full_html=True) # Changed filename to include .html extension

# 3. Descargás el archivo a tu computadora
files.download("Esperanza vs pbi argentina.html")

# 1. Importás la herramienta de descargas de Colab
from google.colab import files

# 2. Guardás el gráfico como un archivo HTML en la memoria de Colab
fig.write_html("Esperanza vs pbi argentina", full_html=True)

# 3. Descargás el archivo a tu computadora
files.download("Esperanza vs pbi argentina.html")

import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pandas as pd
from google.colab import files

# Load df1 and preprocess it within this cell to ensure it's always defined
df1 = pd.read_csv("Life Expectancy Data.csv")
df1.columns = df1.columns.str.strip() # Ensure column names are clean

# Create df_arg from the now-defined df1
df_arg = df1[df1['Country'] == 'Argentina'].sort_values('Year')

# 2. Creamos el lienzo indicando explícitamente el eje Y secundario
fig = make_subplots(specs=[[{"secondary_y": True}]])

# 3. EJE Y IZQUIERDO: Esperanza de Vida (Línea Azul con círculos)
fig.add_trace(
    go.Scatter(
        x=df_arg['Year'],
        y=df_arg['Life expectancy'],
        name="Esperanza de Vida",
        mode='lines+markers',
        line=dict(color='#1f77b4', width=3),
        marker=dict(symbol='circle', size=8)
    ),
    secondary_y=False,
)

# 4. EJE Y DERECHO: PBI (Línea Verde punteada con cuadrados)
fig.add_trace(
    go.Scatter(
        x=df_arg['Year'],
        y=df_arg['GDP'],
        name="PBI (USD)",
        mode='lines+markers',
        line=dict(color='#2ca02c', width=3, dash='dash'), # Línea punteada
        marker=dict(symbol='square', size=8)
    ),
    secondary_y=True,
)

# 5. Título, Estética y la magia de la interactividad unificada
fig.update_layout(
    title_text="Evolución de la Esperanza de Vida vs. PBI en Argentina",
    title_font=dict(size=18, family="Arial"),
    title_x=0.5, # Centrar el título
    plot_bgcolor='white',
    # Al pasar el cursor, muestra los datos de ambas variables en simultáneo
    hovermode="x unified",
    legend=dict(x=0.01, y=0.99, bgcolor='rgba(255, 255, 255, 0.8)')
)

# Formateamos las etiquetas y las cuadrículas de fondo para el estándar del reporte
fig.update_yaxes(title_text="<b>Esperanza de Vida (Años)</b>", color='#1f77b4', secondary_y=False, showgrid=True, gridcolor='lightgrey', gridwidth=1, griddash='dash')
fig.update_yaxes(title_text="<b>PBI (USD)</b>", color='#2ca02c', secondary_y=True, showgrid=False)
fig.update_xaxes(title_text="<b>Año</b>", showgrid=True, gridcolor='lightgrey')

fig.write_html("grafico.html", full_html=True)
files.download('grafico.html')

import plotly.graph_objects as go
from plotly.subplots import make_subplots

# 1. Asumo que el DataFrame filtrado de Argentina ya está guardado en df_arg
# df_arg = df1[df1['Country'] == 'Argentina'].sort_values('Year')

# 2. Creamos el lienzo indicando explícitamente el eje Y secundario
fig = make_subplots(specs=[[{"secondary_y": True}]])

# 3. EJE Y IZQUIERDO: Esperanza de Vida (Línea Azul con círculos)
fig.add_trace(
    go.Scatter(
        x=df_arg['Year'],
        y=df_arg['Life expectancy'],
        name="Esperanza de Vida",
        mode='lines+markers',
        line=dict(color='#1f77b4', width=3),
        marker=dict(symbol='circle', size=8)
    ),
    secondary_y=False,
)

# 4. EJE Y DERECHO: Gasto en Salud Pública (Línea Roja punteada con triángulos)
fig.add_trace(
    go.Scatter(
        x=df_arg['Year'],
        y=df_arg['Total expenditure'],
        name="Inversión en Salud",
        mode='lines+markers',
        line=dict(color='#d62728', width=3, dash='dash'), # Línea punteada
        marker=dict(symbol='triangle-up', size=8)
    ),
    secondary_y=True,
)

# 5. Título, Estética y la magia de la interactividad unificada
fig.update_layout(
    title_text="Evolución: Esperanza de Vida vs. Inversión en Salud Pública (Argentina)",
    title_font=dict(size=18, family="Arial"),
    title_x=0.5, # Centrar el título
    plot_bgcolor='white',
    # Al pasar el cursor, muestra los datos de ambas variables en simultáneo
    hovermode="x unified",
    legend=dict(x=0.01, y=0.99, bgcolor='rgba(255, 255, 255, 0.8)')
)

# Formateamos las etiquetas y las cuadrículas de fondo para el estándar del reporte
fig.update_yaxes(title_text="<b>Esperanza de Vida (Años)</b>", color='#1f77b4', secondary_y=False, showgrid=True, gridcolor='lightgrey', gridwidth=1, griddash='dash')
fig.update_yaxes(title_text="<b>Gasto en Salud (% del gasto total del Gob.)</b>", color='#d62728', secondary_y=True, showgrid=False)
fig.update_xaxes(title_text="<b>Año</b>", showgrid=True, gridcolor='lightgrey')

fig.show()

import plotly.graph_objects as go
from plotly.subplots import make_subplots

# 1. Asumo que el DataFrame filtrado de Argentina ya está guardado en df_arg
# df_arg = df1[df1['Country'] == 'Argentina'].sort_values('Year')

# 2. Creamos el lienzo indicando explícitamente el eje Y secundario
fig = make_subplots(specs=[[{"secondary_y": True}]])

# 3. EJE Y IZQUIERDO: Esperanza de Vida (Línea Azul con círculos)
fig.add_trace(
    go.Scatter(
        x=df_arg['Year'],
        y=df_arg['Life expectancy'],
        name="Esperanza de Vida",
        mode='lines+markers',
        line=dict(color='#1f77b4', width=3),
        marker=dict(symbol='circle', size=8)
    ),
    secondary_y=False,
)

# 4. EJE Y DERECHO: Escolaridad (Línea Púrpura guion-punto con diamantes)
fig.add_trace(
    go.Scatter(
        x=df_arg['Year'],
        y=df_arg['Schooling'],
        name="Escolaridad promedio",
        mode='lines+markers',
        line=dict(color='#9467bd', width=3, dash='dashdot'), # Línea guion-punto
        marker=dict(symbol='diamond', size=8)
    ),
    secondary_y=True,
)

# 5. Título, Estética y la magia de la interactividad unificada
fig.update_layout(
    title_text="Evolución: Esperanza de Vida vs. Nivel de Escolaridad (Argentina)",
    title_font=dict(size=18, family="Arial"),
    title_x=0.5, # Centrar el título
    plot_bgcolor='white',
    # Al pasar el cursor, muestra los datos de ambas variables en simultáneo
    hovermode="x unified",
    legend=dict(x=0.01, y=0.99, bgcolor='rgba(255, 255, 255, 0.8)')
)

# Formateamos las etiquetas y las cuadrículas de fondo para mantener la coherencia
fig.update_yaxes(title_text="<b>Esperanza de Vida (Años)</b>", color='#1f77b4', secondary_y=False, showgrid=True, gridcolor='lightgrey', gridwidth=1, griddash='dash')
fig.update_yaxes(title_text="<b>Escolaridad (Años promedio)</b>", color='#9467bd', secondary_y=True, showgrid=False)
fig.update_xaxes(title_text="<b>Año</b>", showgrid=True, gridcolor='lightgrey')

fig.show()

import plotly.express as px
import pandas as pd

# Load dataframes
df1 = pd.read_csv("Life Expectancy Data.csv")
df2 = pd.read_excel("2015.year.xlsx")

# Strip whitespace from column names in both df1 and df2
df1.columns = df1.columns.str.strip()
df2.columns = df2.columns.str.strip()

# Filter df1 for the year 2015
df1_2015_filtered = df1[df1['Year'] == 2015]

# Merge df1_2015_filtered with df2 on 'Country'. Assuming df2 implicitly contains 2015 data.
df_merged_2015 = pd.merge(df1_2015_filtered, df2, on='Country', how='inner', suffixes=('_df1', '_df2'))

# Rename columns to match the plotting function's expectations
df_merged_2015 = df_merged_2015.rename(columns={
    'Happiness Score': 'Happiness_Score',
    'Trust (Government Corruption)': 'Trust_Government_Corruption',
    'Economy (GDP per Capita)': 'Economy_GDP_per_Capita' # Add this if used later
})

# Assign to df_2015_analysis after dropping NaNs and explicitly create a copy
df_2015_analysis = df_merged_2015.dropna(subset=['Life expectancy', 'Happiness_Score', 'Region', 'GDP']).copy()

# 1. EL TRUCO: Limpiar los nombres para que Plotly reconozca TODOS los países
# Apply cleaning to df_2015_analysis
df_2015_analysis['Country'] = df_2015_analysis['Country'].str.strip() # Saca espacios vacíos por accidente

diccionario_oms = {
    'United States of America': 'United States',
    'Bolivia (Plurinational State of)': 'Bolivia',
    'Venezuela (Bolivarian Republic of)': 'Venezuela',
    'Iran (Islamic Republic of)': 'Iran',
    'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom',
    'Republic of Korea': 'South Korea',
    'Democratic People\'s Republic of Korea': 'North Korea',
    'Russian Federation': 'Russia',
    'Syrian Arab Republic': 'Syria',
    'Republic of Moldova': 'Moldova',
    'Lao People\'s Democratic Republic': 'Laos',
    'United Republic of Tanzania': 'Tanzania',
    'Viet Nam': 'Vietnam'
}

# Aplicamos el diccionario para reemplazar los nombres conflictivos
df_2015_analysis['Country'] = df_2015_analysis['Country'].replace(diccionario_oms)

# 2. CREACIÓN DEL MAPA DINÁMICO
columna_vida = 'Life expectancy' # Corrected column name, no trailing space

fig = px.choropleth(
    df_2015_analysis,
    locations="Country",
    locationmode="country names",
    color=columna_vida,
    hover_name="Country",
    color_continuous_scale="RdYlGn",
    title="Mapa de Calor Global: Esperanza de Vida al Nacer",
    labels={columna_vida: 'Esperanza de Vida (Años)'}
)

# 3. ESTÉTICA PROFESIONAL
fig.update_layout(
    geo=dict(
        showframe=False,
        showcoastlines=True,
        projection_type='equirectangular'
    ),
    title_font_size=20,
    title_x=0.5,
    margin={"r":0,"t":50,"l":0,"b":0}
)

fig.show()

# Buscamos cómo están escritos los países que se ven grises en tu mapa
paises_grises = ["United", "Russia", "Congo", "Egypt", "Iran", "Ivory", "Korea", "Syria"]

for pais in paises_grises:
    nombres_en_tu_df = df_2015_analysis[df_2015_analysis['Country'].str.contains(pais, case=False, na=False)]['Country'].unique()
    print(f"Buscando '{pais}': {nombres_en_tu_df}")
