# -*- coding: utf-8 -*-
"""Expectativa de vida prueba- 29/04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V2XoEx_0zsXFa9DL0tfBglXuar_wh7K6
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df1 = pd.read_csv("Life Expectancy Data.csv")

df1 = df1.dropna(subset=['Life expectancy '])
df1 = df1[df1['Life expectancy '] != 0]

df1.columns = df1.columns.str.strip()

df1.head()

len(df1)

df1.columns

df1.shape

df1.describe()

df1.info()

df1.columns = df1.columns.str.strip()

df1["Life expectancy"].max()
print("El maximo de expectativa de vida:", df1["Life expectancy"].max())

df1["Life expectancy"].min()
print("El minimo de expectativa de vida:", df1["Life expectancy"].min())

"""**Código de abajo**. Agrupa el dataset según dos variables: la esperanza de vida ("Life expectancy") y el país ("Country"). Es decir, junta todas las filas que tienen el mismo valor de esperanza de vida y pertenecen al mismo país.

Luego, sobre cada grupo formado, aplica la función "count()", que cuenta cuántos valores NO nulos (no vacíos) hay en cada columna.

Por eso, los números que aparecen (1, 0, etc.) no son valores del dataset original, sino cantidades de datos disponibles dentro de cada grupo.
"""

df1.groupby(["Life expectancy" , "Country"]).count()

"""**Código de abajo.**Este código agrupa el dataset por país ("Country"), es decir, junta todas las filas que pertenecen al mismo país (por ejemplo, todos los años de Argentina, todos los años de Francia, etc.).
Luego selecciona solo dos variables: "Life expectancy" y "infant deaths".
Después aplica la función "nunique()", que cuenta cuántos valores distintos (únicos) hay en cada una de esas columnas dentro de cada país.

El resultado muestra, para cada país:
cuántos valores diferentes de esperanza de vida tuvo a lo largo del tiempo
cuántos valores diferentes de muertes infantiles tuvo
Por ejemplo:
Afghanistan → 14 en "Life expectancy"
significa que, a lo largo de los años, tuvo 14 valores distintos de esperanza de vida
Albania → 16
significa que en el dataset tiene 16 valores distintos (probablemente 16 años con datos distintos)
En general:
números altos → la variable cambia bastante a lo largo del tiempo en ese país
números bajos → la variable cambia poco o se repite
Importante:
Esto no cuenta cuántos datos hay, sino cuántos valores diferentes hay.
"""

df1.groupby('Country')[['Life expectancy', 'infant deaths']].nunique()

mean_study_hours = df1["Life expectancy"].mean()
print("El promedio de expectativa de vida es:", mean_study_hours)

df1.sort_values("Life expectancy", ascending=False).head()

df1.sort_values("Life expectancy", ascending=True).head()

df1.info()

"""Código de abajo. cuántas veces se repite cada país en el dataset (supongo que por años)"""

df1["Country"].value_counts()

"""**Código de abajo**. Este código toma la columna "Life expectancy" (esperanza de vida) y cuenta cuántas veces aparece cada valor dentro del dataset.

El resultado muestra una tabla donde:
a la izquierda están los valores de esperanza de vida
a la derecha está la cantidad de veces que aparece cada uno
Por ejemplo: 73.0 → 45 significa que el valor 73.0 aparece 45 veces en el dataset
75.0 → 33 significa que aparece 33 veces
83.4 → 1 significa que ese valor aparece una sola vez

En general
valores con números altos → son más comunes en el dataset
valores con 1 → son poco frecuentes o únicos
Importante:
Esto no agrupa por país ni por año, simplemente cuenta frecuencias totales en toda la base.
Sirve para entender:
qué valores de esperanza de vida son más frecuentes
cómo se distribuyen los datos
si hay valores raros o poco comunes
"""

df1["Life expectancy"].value_counts()

"""Código de abajo. Lo mismo que el value count de arriba solo que en relación a la mortalidad de adultos. 34 veces se repite el 12.0, 30 veces el 14.0 y así"""

df1["Adult Mortality"].value_counts()

df1['GDP (in thousands)'] = df1['GDP'] / 1000
display(df1[['Country', 'Year', 'GDP', 'GDP (in thousands)']].head())

"""Código de abajo. Este código selecciona tres columnas del dataset: el país ("Country"), los años de educación ("Schooling") y la tasa de HIV/AIDS.

Luego aplica la función "value_counts()", que cuenta cuántas veces aparece cada combinación exacta de esos tres valores.

Es decir, agrupa por combinaciones únicas de:
Country
Schooling
HIV/AIDS
y cuenta cuántas filas tienen exactamente esos mismos valores.

El resultado muestra:
cada combinación única de (Country, Schooling, HIV/AIDS)
cuántas veces se repite en el dataset
"""

df1[["Country" , "Schooling" , "HIV/AIDS"]].value_counts()

"""Código de abajo. Toma la columna Schooling (años de escolaridad) y usa cada valor distinto como criterio de agrupación del dataset.
El resultado muestra una tabla donde:

a la izquierda están los valores únicos de Schooling (por ejemplo 0.0, 10.5, 15.2, etc.)
a la derecha aparece, para cada columna del dataset, cuántos datos no nulos (no NaN) existen dentro de cada grupo de Schooling.

Es decir, NO cuenta cuántas veces aparece Schooling, sino que, para cada valor de Schooling, cuenta cuántos registros tienen datos válidos en cada variable.
Por ejemplo:
Schooling = 0.0
Life expectancy → 26
Alcohol → 17
GDP → 28

Esto significa que, para los países/años con escolaridad igual a 0.0:

hay 26 valores no nulos de esperanza de vida
solo 17 valores no nulos de alcohol
28 valores no nulos de GDP



Las diferencias entre columnas se deben a la presencia de datos faltantes (NaN).
En general:

números altos → esa variable tiene pocos o ningún dato faltante para ese nivel de Schooling
números más bajos → esa variable tiene muchos valores faltantes en ese grupo
"""

df1.groupby("Schooling").count()

"""Código de abajo. Este código filtra el dataset y se queda únicamente con las filas donde la esperanza de vida (Life expectancy) es menor a 50.
El resultado muestra:

países y años con niveles muy bajos de esperanza de vida
todas las columnas originales del dataset
solo los casos que cumplen esa condición

En general:

valores menores a 50 → países con situaciones sanitarias críticas
valores muy bajos → posibles crisis, epidemias o contextos de extrema pobreza

Importante:

no agrupa países
un mismo país puede aparecer varias veces (uno por cada año)
"""

df1[df1['Life expectancy']< 50.0]

"""Código de abajo. Agrupa el dataset por país y calcula el promedio de la esperanza de vida y de los años de escolaridad para cada país.
El resultado muestra una tabla donde: a la izquierda están los países
a la derecha aparecen:
el promedio de Life expectancy
el promedio de Schooling
Cada fila representa un país, no un país por año.
Cómo funciona el código paso a paso
groupby("Country")
agrupa todas las filas que pertenecen al mismo país, sin importar el año.
Es decir:
junta todos los registros de Afghanistan
junta todos los registros de Albania
y así con cada país
.agg({...})
indica qué operación estadística se quiere hacer sobre cada columna.
"Life expectancy": "mean"
calcula la esperanza de vida promedio del país considerando todos los años disponibles
"Schooling": "mean"
calcula el promedio de años de escolaridad del país, también usando todos los años.
"""

df1.groupby("Country").agg({"Life expectancy":"mean", "Schooling":"mean"})

"""Código de abajo. agrupa el dataset por país y calcula el promedio de HIV/AIDS, años de escolaridad y GDP para cada país.
El resultado muestra una tabla donde:

a la izquierda están los países
a la derecha aparecen:

el promedio de HIV/AIDS
el promedio de Schooling
el promedio de GDP
Cada fila representa un país, no un país por año
Cómo funciona el código paso a paso
groupby("Country")
agrupa todas las filas que pertenecen al mismo país, juntando todos los años disponibles de ese país.
.agg({...})
permite aplicar distintas operaciones estadísticas a distintas columnas al mismo tiempo.
"HIV/AIDS": "mean"
calcula el valor promedio de HIV/AIDS del país considerando todos los años.
"Schooling": "mean"
calcula el promedio de años de escolaridad del país a lo largo del tiempo.
"GDP": "mean"
calcula el GDP promedio del país considerando todos los registros disponibles.
"""

df1.groupby("Country").agg({"HIV/AIDS":"mean", "Schooling":"mean", "GDP":"mean"})

import matplotlib.pyplot as plt
df1.plot(kind="scatter", x="Schooling", y="Life expectancy")
plt.title("Life Expectancy vs Schooling")
plt.show()

import matplotlib.pyplot as plt
plt.scatter(df1["HIV/AIDS"], df1["Life expectancy"])
plt.xlabel("HIV/AIDS")
plt.ylabel("Life expectancy ")
plt.title("Life expectancy vs HIV/AIDS")
plt.show()

import seaborn as sns

sns.regplot(x="Adult Mortality", y="Life expectancy", data=df1 , color="yellow")
plt.title("Life expectancy vs Adult Mortality")
plt.show()

import matplotlib.pyplot as plt
plt.scatter(df1["GDP"], df1["Life expectancy"], color="purple")
plt.xlabel("GDP")
plt.ylabel("Life expectancy")
plt.title("Life expectancy vs GDP")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

sns.regplot(x="infant deaths", y="Life expectancy", data=df1, color='orange')
plt.title("Expectativa de vida vs Mortalidad Infantil")
plt.show()

plt.scatter(df1["Income composition of resources"], df1["Life expectancy"], color='red')
plt.xlabel("Income composition")
plt.ylabel("Life expectancy")
plt.title("Life expectancy vs Income composition")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
import requests
from io import BytesIO

# 1. Cargar dataset
df1 = pd.read_csv('Life Expectancy')

# 2. Filtrar año 2015 y limpiar datos
df1_2015 = df1[df1['Year'] == 2015].dropna(subset=['Life expectancy'])

# 3. Ordenar por expectativa de vida (descendente) y tomar top 30
df1_top30 = df1_2015.sort_values(by='Life expectancy', ascending=False).head(30)

countries = df1_top30['Country'].tolist()
life_exp = df1_top30['Life expectancy'].tolist()

# 4. Diccionario de banderas (FlagCDN) con nombres exactos del dataset
flag_urls = {
    "Japan": "https://flagcdn.com/w320/jp.png",
    "Switzerland": "https://flagcdn.com/w320/ch.png",
    "Australia": "https://flagcdn.com/w320/au.png",
    "Spain": "https://flagcdn.com/w320/es.png",
    "Italy": "https://flagcdn.com/w320/it.png",
    "France": "https://flagcdn.com/w320/fr.png",
    "Sweden": "https://flagcdn.com/w320/se.png",
    "Norway": "https://flagcdn.com/w320/no.png",
    "Netherlands": "https://flagcdn.com/w320/nl.png",
    "United Kingdom": "https://flagcdn.com/w320/gb.png",
    "Germany": "https://flagcdn.com/w320/de.png",
    "Canada": "https://flagcdn.com/w320/ca.png",
    "New Zealand": "https://flagcdn.com/w320/nz.png",
    "Austria": "https://flagcdn.com/w320/at.png",
    "Belgium": "https://flagcdn.com/w320/be.png",
    "Denmark": "https://flagcdn.com/w320/dk.png",
    "Finland": "https://flagcdn.com/w320/fi.png",
    "Ireland": "https://flagcdn.com/w320/ie.png",
    "Portugal": "https://flagcdn.com/w320/pt.png",
    "Greece": "https://flagcdn.com/w320/gr.png",
    "Israel": "https://flagcdn.com/w320/il.png",
    "Iceland": "https://flagcdn.com/w320/is.png",
    "Singapore": "https://flagcdn.com/w320/sg.png",
    "Republic of Korea": "https://flagcdn.com/w320/kr.png",
    "Slovenia": "https://flagcdn.com/w320/si.png",
    "Luxembourg": "https://flagcdn.com/w320/lu.png",
    "Malta": "https://flagcdn.com/w320/mt.png",
    "Cyprus": "https://flagcdn.com/w320/cy.png",
    "Costa Rica": "https://flagcdn.com/w320/cr.png",
    "Chile": "https://flagcdn.com/w320/cl.png"
}

# 5. Función para obtener banderas
def get_flag(country):
    try:
        url = flag_urls[country]
        response = requests.get(url, timeout=5)
        img = Image.open(BytesIO(response.content))
        return img
    except:
        return None

# 6. Crear figura
plt.figure(figsize=(14, 10))

# 7. Dibujar "barras" con banderas + recuadro negro + texto
for i, country in enumerate(countries):
    img = get_flag(country)
    if img:
        bar_width = int(life_exp[i] * 6)   # ancho proporcional
        img = img.resize((bar_width, 25)) # altura fija
        # ✅ ya no aplicamos flips, solo origin="upper"
        plt.imshow(
            img,
            extent=[0, life_exp[i], i - 0.4, i + 0.4],
            aspect='auto',
            origin="lower"
        )
        # Recuadro negro alrededor de la barra
        plt.plot([0, life_exp[i], life_exp[i], 0, 0],
                 [i - 0.4, i - 0.4, i + 0.4, i + 0.4, i - 0.4],
                 color="black", linewidth=1)

        # Número exacto al final de la barra
        plt.text(
            life_exp[i] + 0.5, i, f"{life_exp[i]:.1f}",
            va='center', ha='left', fontsize=9, color="black"
        )

# 8. Ejes y etiquetas
plt.yticks(range(len(countries)), countries, fontsize=9)
plt.xlabel("Expectativa de vida")
plt.title("Top 30 países con mayor expectativa de vida (2015) - Banderas orientadas correctamente")

plt.gca().invert_yaxis()
plt.xlim(0, max(life_exp) + 5)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
import requests
from io import BytesIO


# 2. Filtrar año 2015 y limpiar datos
df1_2015 = df1[df1['Year'] == 2015].dropna(subset=['Life expectancy'])

# 3. Ordenar por expectativa de vida (descendente) y tomar top 30
df1_top30 = df1_2015.sort_values(by='Life expectancy', ascending=False).head(30)

countries = df1_top30['Country'].tolist()
life_exp = df1_top30['Life expectancy'].tolist()

# 4. Diccionario de banderas (FlagCDN) con nombres exactos del dataset
flag_urls = {
    "Japan": "https://flagcdn.com/w320/jp.png",
    "Switzerland": "https://flagcdn.com/w320/ch.png",
    "Australia": "https://flagcdn.com/w320/au.png",
    "Spain": "https://flagcdn.com/w320/es.png",
    "Italy": "https://flagcdn.com/w320/it.png",
    "France": "https://flagcdn.com/w320/fr.png",
    "Sweden": "https://flagcdn.com/w320/se.png",
    "Norway": "https://flagcdn.com/w320/no.png",
    "Netherlands": "https://flagcdn.com/w320/nl.png",
    "United Kingdom": "https://flagcdn.com/w320/gb.png",
    "Germany": "https://flagcdn.com/w320/de.png",
    "Canada": "https://flagcdn.com/w320/ca.png",
    "New Zealand": "https://flagcdn.com/w320/nz.png",
    "Austria": "https://flagcdn.com/w320/at.png",
    "Belgium": "https://flagcdn.com/w320/be.png",
    "Denmark": "https://flagcdn.com/w320/dk.png",
    "Finland": "https://flagcdn.com/w320/fi.png",
    "Ireland": "https://flagcdn.com/w320/ie.png",
    "Portugal": "https://flagcdn.com/w320/pt.png",
    "Greece": "https://flagcdn.com/w320/gr.png",
    "Israel": "https://flagcdn.com/w320/il.png",
    "Iceland": "https://flagcdn.com/w320/is.png",
    "Singapore": "https://flagcdn.com/w320/sg.png",
    "Republic of Korea": "https://flagcdn.com/w320/kr.png",
    "Slovenia": "https://flagcdn.com/w320/si.png",
    "Luxembourg": "https://flagcdn.com/w320/lu.png",
    "Malta": "https://flagcdn.com/w320/mt.png",
    "Cyprus": "https://flagcdn.com/w320/cy.png",
    "Costa Rica": "https://flagcdn.com/w320/cr.png",
    "Chile": "https://flagcdn.com/w320/cl.png"
}

# 5. Función para obtener banderas normalizadas (sin deformación)
TARGET_W = 320
TARGET_H = 160  # ratio 2:1

def get_flag(country):
    try:
        url = flag_urls[country]
        response = requests.get(url, timeout=5)
        img = Image.open(BytesIO(response.content)).convert("RGBA")
        img.thumbnail((TARGET_W, TARGET_H), Image.LANCZOS)
        canvas = Image.new("RGBA", (TARGET_W, TARGET_H), (255, 255, 255, 255))
        offset_x = (TARGET_W - img.width) // 2
        offset_y = (TARGET_H - img.height) // 2
        canvas.paste(img, (offset_x, offset_y))
        return canvas
    except:
        return None

# 6. Crear figura
plt.figure(figsize=(14, 10))

# 7. Dibujar barras con banderas + recuadro negro + texto
bar_height = 0.75

for i, country in enumerate(countries):
    img = get_flag(country)
    if img:
        plt.imshow(
            img,
            extent=[0, life_exp[i], i - bar_height/2, i + bar_height/2],
            aspect='auto',
            origin='upper'
        )
        plt.plot([0, life_exp[i], life_exp[i], 0, 0],
                 [i - bar_height/2, i - bar_height/2, i + bar_height/2, i + bar_height/2, i - bar_height/2],
                 color="black", linewidth=1)
        plt.text(
            life_exp[i] + 0.5, i, f"{life_exp[i]:.1f}",
            va='center', ha='left', fontsize=9, color="black"
        )

# 8. Ejes y etiquetas
plt.yticks(range(len(countries)), countries, fontsize=9)
plt.xlabel("Expectativa de vida")
plt.title("Top 30 países con mayor expectativa de vida (2015)")

plt.gca().invert_yaxis()
plt.xlim(0, max(life_exp) + 5)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.offsetbox import OffsetImage, AnnotationBbox
from PIL import Image
import requests
from io import BytesIO
import numpy as np

# 2. Filtrar año 2015 y limpiar datos
df1_2015 = df1[df1['Year'] == 2015].dropna(subset=['Life expectancy'])

# 3. Ordenar por expectativa de vida (descendente) y tomar top 30
df1_top30 = df1_2015.sort_values(by='Life expectancy', ascending=False).head(30)

countries = df1_top30['Country'].tolist()
life_exp = df1_top30['Life expectancy'].tolist()

# 4. Diccionario de banderas
flag_urls = {
    "Japan": "https://flagcdn.com/w320/jp.png",
    "Switzerland": "https://flagcdn.com/w320/ch.png",
    "Australia": "https://flagcdn.com/w320/au.png",
    "Spain": "https://flagcdn.com/w320/es.png",
    "Italy": "https://flagcdn.com/w320/it.png",
    "France": "https://flagcdn.com/w320/fr.png",
    "Sweden": "https://flagcdn.com/w320/se.png",
    "Norway": "https://flagcdn.com/w320/no.png",
    "Netherlands": "https://flagcdn.com/w320/nl.png",
    "United Kingdom": "https://flagcdn.com/w320/gb.png",
    "Germany": "https://flagcdn.com/w320/de.png",
    "Canada": "https://flagcdn.com/w320/ca.png",
    "New Zealand": "https://flagcdn.com/w320/nz.png",
    "Austria": "https://flagcdn.com/w320/at.png",
    "Belgium": "https://flagcdn.com/w320/be.png",
    "Denmark": "https://flagcdn.com/w320/dk.png",
    "Finland": "https://flagcdn.com/w320/fi.png",
    "Ireland": "https://flagcdn.com/w320/ie.png",
    "Portugal": "https://flagcdn.com/w320/pt.png",
    "Greece": "https://flagcdn.com/w320/gr.png",
    "Israel": "https://flagcdn.com/w320/il.png",
    "Iceland": "https://flagcdn.com/w320/is.png",
    "Singapore": "https://flagcdn.com/w320/sg.png",
    "Republic of Korea": "https://flagcdn.com/w320/kr.png",
    "Slovenia": "https://flagcdn.com/w320/si.png",
    "Luxembourg": "https://flagcdn.com/w320/lu.png",
    "Malta": "https://flagcdn.com/w320/mt.png",
    "Cyprus": "https://flagcdn.com/w320/cy.png",
    "Costa Rica": "https://flagcdn.com/w320/cr.png",
    "Chile": "https://flagcdn.com/w320/cl.png"
}

# 5. Función para obtener bandera como array
def get_flag(country):
    try:
        url = flag_urls[country]
        response = requests.get(url, timeout=5)
        img = Image.open(BytesIO(response.content)).convert("RGB")
        img = img.resize((80, 50), Image.LANCZOS)  # tamaño fijo con buen ratio
        return np.array(img)
    except:
        return None

# 6. Crear figura y eje
fig, ax = plt.subplots(figsize=(14, 12))

min_val = min(life_exp)

for i, country in enumerate(countries):
    # Barra de fondo gris
    ax.barh(i, life_exp[i], color="#e0e0e0", edgecolor="black", linewidth=0.8, height=0.7)

    # Bandera pegada al inicio de la barra (esquina izquierda)
    img_arr = get_flag(country)
    if img_arr is not None:
        im = OffsetImage(img_arr, zoom=0.55)
        ab = AnnotationBbox(
            im,
            (min_val + 0.3, i),   # posición: pegada al inicio de la barra
            frameon=True,
            box_alignment=(0, 0.5),
            bboxprops=dict(edgecolor="black", linewidth=0.8)
        )
        ax.add_artist(ab)

    # Valor al final de la barra
    ax.text(life_exp[i] + 0.2, i, f"{life_exp[i]:.1f}",
            va='center', ha='left', fontsize=9)

# 7. Ejes y formato
ax.set_yticks(range(len(countries)))
ax.set_yticklabels(countries, fontsize=9)
ax.set_xlabel("Expectativa de vida (años)", fontsize=11)
ax.set_title("Top 30 países con mayor expectativa de vida (2015)", fontsize=13, fontweight='bold')
ax.invert_yaxis()
ax.set_xlim(0, max(life_exp) + 5)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.offsetbox import OffsetImage, AnnotationBbox
from PIL import Image
import requests
from io import BytesIO
import numpy as np

# 2. Filtrar año 2015 y limpiar datos
df1_2015 = df1[df1['Year'] == 2015].dropna(subset=['Life expectancy'])

# 3. Ordenar por expectativa de vida (descendente) y tomar top 30
df1_top30 = df1_2015.sort_values(by='Life expectancy', ascending=False).head(30)

countries = df1_top30['Country'].tolist()
life_exp = df1_top30['Life expectancy'].tolist()

# 4. Diccionario de banderas
flag_urls = {
    "Japan": "https://flagcdn.com/w320/jp.png",
    "Switzerland": "https://flagcdn.com/w320/ch.png",
    "Australia": "https://flagcdn.com/w320/au.png",
    "Spain": "https://flagcdn.com/w320/es.png",
    "Italy": "https://flagcdn.com/w320/it.png",
    "France": "https://flagcdn.com/w320/fr.png",
    "Sweden": "https://flagcdn.com/w320/se.png",
    "Norway": "https://flagcdn.com/w320/no.png",
    "Netherlands": "https://flagcdn.com/w320/nl.png",
    "United Kingdom": "https://flagcdn.com/w320/gb.png",
    "Germany": "https://flagcdn.com/w320/de.png",
    "Canada": "https://flagcdn.com/w320/ca.png",
    "New Zealand": "https://flagcdn.com/w320/nz.png",
    "Austria": "https://flagcdn.com/w320/at.png",
    "Belgium": "https://flagcdn.com/w320/be.png",
    "Denmark": "https://flagcdn.com/w320/dk.png",
    "Finland": "https://flagcdn.com/w320/fi.png",
    "Ireland": "https://flagcdn.com/w320/ie.png",
    "Portugal": "https://flagcdn.com/w320/pt.png",
    "Greece": "https://flagcdn.com/w320/gr.png",
    "Israel": "https://flagcdn.com/w320/il.png",
    "Iceland": "https://flagcdn.com/w320/is.png",
    "Singapore": "https://flagcdn.com/w320/sg.png",
    "Republic of Korea": "https://flagcdn.com/w320/kr.png",
    "Slovenia": "https://flagcdn.com/w320/si.png",
    "Luxembourg": "https://flagcdn.com/w320/lu.png",
    "Malta": "https://flagcdn.com/w320/mt.png",
    "Cyprus": "https://flagcdn.com/w320/cy.png",
    "Costa Rica": "https://flagcdn.com/w320/cr.png",
    "Chile": "https://flagcdn.com/w320/cl.png"
}

# 5. Función: descarga bandera, saca color dominante y miniatura
def get_flag_data(country):
    try:
        url = flag_urls[country]
        response = requests.get(url, timeout=5)
        img = Image.open(BytesIO(response.content)).convert("RGB")

        # Color dominante (promedio excluyendo píxeles muy claros/oscuros)
        arr = np.array(img).reshape(-1, 3).astype(float)
        brightness = arr.mean(axis=1)
        mask = (brightness > 30) & (brightness < 220)
        filtered = arr[mask] if mask.sum() > 0 else arr
        dominant = tuple((filtered.mean(axis=0) / 255).tolist())

        # Miniatura para poner al costado
        thumb = img.resize((60, 38), Image.LANCZOS)
        return dominant, np.array(thumb)
    except:
        return (0.6, 0.6, 0.6), None

# 6. Pre-cargar banderas
print("Descargando banderas...")
flag_data = {c: get_flag_data(c) for c in countries}
print("Listo!")

# 7. Crear figura con margen izquierdo para las banderas
fig, ax = plt.subplots(figsize=(14, 12))
plt.subplots_adjust(left=0.28)

for i, country in enumerate(countries):
    color, thumb = flag_data[country]

    # Barra con color dominante de la bandera
    ax.barh(i, life_exp[i], color=color, edgecolor="black", linewidth=0.8, height=0.7)

    # Valor al final de la barra
    ax.text(life_exp[i] + 0.2, i, f"{life_exp[i]:.1f}",
            va='center', ha='left', fontsize=9)

    # Bandera a la izquierda del nombre del país
    if thumb is not None:
        im = OffsetImage(thumb, zoom=0.55)
        ab = AnnotationBbox(
            im,
            xy=(0, i),
            xycoords=('axes fraction', 'data'),
            box_alignment=(1.15, 0.5),
            frameon=True,
            bboxprops=dict(edgecolor="gray", linewidth=0.6)
        )
        ax.add_artist(ab)

# 8. Ejes y formato
ax.set_yticks(range(len(countries)))
ax.set_yticklabels(countries, fontsize=9)
ax.set_xlabel("Expectativa de vida (años)", fontsize=11)
ax.set_title("Top 30 países con mayor expectativa de vida (2015)", fontsize=13, fontweight='bold')
ax.invert_yaxis()
ax.set_xlim(0, max(life_exp) + 5)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.show()

import matplotlib.pyplot as plt
from matplotlib.offsetbox import OffsetImage, AnnotationBbox
from PIL import Image
import requests
from io import BytesIO
import numpy as np

# 2. Filtrar año 2015 y limpiar datos
df1_2015 = df1[df1['Year'] == 2015].dropna(subset=['Life expectancy'])

# 3. Ordenar por expectativa de vida (descendente) y tomar top 30
df1_top30 = df1_2015.sort_values(by='Life expectancy', ascending=False).head(30)

countries = df1_top30['Country'].tolist()
life_exp = df1_top30['Life expectancy'].tolist()

# 4. Diccionario de banderas
flag_urls = {
    "Japan": "https://flagcdn.com/w320/jp.png",
    "Switzerland": "https://flagcdn.com/w320/ch.png",
    "Australia": "https://flagcdn.com/w320/au.png",
    "Spain": "https://flagcdn.com/w320/es.png",
    "Italy": "https://flagcdn.com/w320/it.png",
    "France": "https://flagcdn.com/w320/fr.png",
    "Sweden": "https://flagcdn.com/w320/se.png",
    "Norway": "https://flagcdn.com/w320/no.png",
    "Netherlands": "https://flagcdn.com/w320/nl.png",
    "United Kingdom": "https://flagcdn.com/w320/gb.png",
    "Germany": "https://flagcdn.com/w320/de.png",
    "Canada": "https://flagcdn.com/w320/ca.png",
    "New Zealand": "https://flagcdn.com/w320/nz.png",
    "Austria": "https://flagcdn.com/w320/at.png",
    "Belgium": "https://flagcdn.com/w320/be.png",
    "Denmark": "https://flagcdn.com/w320/dk.png",
    "Finland": "https://flagcdn.com/w320/fi.png",
    "Ireland": "https://flagcdn.com/w320/ie.png",
    "Portugal": "https://flagcdn.com/w320/pt.png",
    "Greece": "https://flagcdn.com/w320/gr.png",
    "Israel": "https://flagcdn.com/w320/il.png",
    "Iceland": "https://flagcdn.com/w320/is.png",
    "Singapore": "https://flagcdn.com/w320/sg.png",
    "Republic of Korea": "https://flagcdn.com/w320/kr.png",
    "Slovenia": "https://flagcdn.com/w320/si.png",
    "Luxembourg": "https://flagcdn.com/w320/lu.png",
    "Malta": "https://flagcdn.com/w320/mt.png",
    "Cyprus": "https://flagcdn.com/w320/cy.png",
    "Costa Rica": "https://flagcdn.com/w320/cr.png",
    "Chile": "https://flagcdn.com/w320/cl.png"
}

# 5. Color principal real de cada bandera
flag_colors = {
    "Japan":            "#BC002D",
    "Switzerland":      "#FF0000",
    "Australia":        "#00008B",
    "Spain":            "#c60b1e",
    "Italy":            "#009246",
    "France":           "#002395",
    "Sweden":           "#006AA7",
    "Norway":           "#EF2B2D",
    "Netherlands":      "#AE1C28",
    "United Kingdom":   "#012169",
    "Germany":          "#000000",
    "Canada":           "#FF0000",
    "New Zealand":      "#00247D",
    "Austria":          "#ED2939",
    "Belgium":          "#000000",
    "Denmark":          "#C60C30",
    "Finland":          "#003580",
    "Ireland":          "#169B62",
    "Portugal":         "#006600",
    "Greece":           "#0D5EAF",
    "Israel":           "#0038B8",
    "Iceland":          "#003897",
    "Singapore":        "#EF3340",
    "Republic of Korea":"#CD2E3A",
    "Slovenia":         "#003DA5",
    "Luxembourg":       "#EF3340",
    "Malta":            "#CF142B",
    "Cyprus":           "#4E90A0",
    "Costa Rica":       "#002B7F",
    "Chile":            "#D52B1E",
}

# 6. Función para obtener miniatura de bandera
def get_flag(country):
    try:
        url = flag_urls[country]
        response = requests.get(url, timeout=5)
        img = Image.open(BytesIO(response.content)).convert("RGB")
        img = img.resize((60, 38), Image.LANCZOS)
        return np.array(img)
    except:
        return None

# 7. Pre-cargar miniaturas
print("Descargando banderas...")
flag_thumbs = {c: get_flag(c) for c in countries}
print("Listo!")

# 8. Figura — margen derecho amplio para banderas
fig, ax = plt.subplots(figsize=(16, 12))
plt.subplots_adjust(right=0.82)  # espacio a la derecha para las banderas

for i, country in enumerate(countries):
    color = flag_colors.get(country, "#888888")
    thumb = flag_thumbs[country]

    # Barra con color real de la bandera
    ax.barh(i, life_exp[i], color=color, edgecolor="black", linewidth=0.8, height=0.7)

    # Valor numérico al final de la barra
    ax.text(life_exp[i] + 0.2, i, f"{life_exp[i]:.1f}",
            va='center', ha='left', fontsize=9)

    # Bandera a la derecha del número
    if thumb is not None:
        im = OffsetImage(thumb, zoom=0.6)
        ab = AnnotationBbox(
            im,
            xy=(1, i),
            xycoords=('axes fraction', 'data'),
            box_alignment=(-0.2, 0.5),
            frameon=True,
            bboxprops=dict(edgecolor="gray", linewidth=0.6)
        )
        ax.add_artist(ab)

# 9. Ejes y formato
ax.set_yticks(range(len(countries)))
ax.set_yticklabels(countries, fontsize=9)
ax.set_xlabel("Expectativa de vida (años)", fontsize=11)
ax.set_title("Top 30 países con mayor expectativa de vida (2015)", fontsize=13, fontweight='bold')
ax.invert_yaxis()
ax.set_xlim(0, max(life_exp) + 5)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.show()

import matplotlib.pyplot as plt
from matplotlib.offsetbox import OffsetImage, AnnotationBbox
from PIL import Image
import requests
from io import BytesIO
import numpy as np

# 2. Filtrar año 2015 y limpiar datos
df1_2015 = df1[df1['Year'] == 2015].dropna(subset=['Life expectancy'])

# 3. Ordenar ASCENDENTE y tomar los 30 con MENOR expectativa de vida
df1_bottom30 = df1_2015.sort_values(by='Life expectancy', ascending=True).head(30)

countries = df1_bottom30['Country'].tolist()
life_exp = df1_bottom30['Life expectancy'].tolist()

# 4. Diccionario de banderas
flag_urls = {
    "Sierra Leone": "https://flagcdn.com/w320/sl.png",
    "Central African Republic": "https://flagcdn.com/w320/cf.png",
    "Chad": "https://flagcdn.com/w320/td.png",
    "Nigeria": "https://flagcdn.com/w320/ng.png",
    "Lesotho": "https://flagcdn.com/w320/ls.png",
    "Côte d'Ivoire": "https://flagcdn.com/w320/ci.png",
    "Swaziland": "https://flagcdn.com/w320/sz.png",
    "Angola": "https://flagcdn.com/w320/ao.png",
    "Cameroon": "https://flagcdn.com/w320/cm.png",
    "Somalia": "https://flagcdn.com/w320/so.png",
    "Guinea-Bissau": "https://flagcdn.com/w320/gw.png",
    "Mozambique": "https://flagcdn.com/w320/mz.png",
    "Mali": "https://flagcdn.com/w320/ml.png",
    "Zambia": "https://flagcdn.com/w320/zm.png",
    "Burkina Faso": "https://flagcdn.com/w320/bf.png",
    "Uganda": "https://flagcdn.com/w320/ug.png",
    "Malawi": "https://flagcdn.com/w320/mw.png",
    "Guinea": "https://flagcdn.com/w320/gn.png",
    "Congo": "https://flagcdn.com/w320/cg.png",
    "South Sudan": "https://flagcdn.com/w320/ss.png",
    "Burundi": "https://flagcdn.com/w320/bi.png",
    "Niger": "https://flagcdn.com/w320/ne.png",
    "Benin": "https://flagcdn.com/w320/bj.png",
    "Equatorial Guinea": "https://flagcdn.com/w320/gq.png",
    "Côte d'Ivoire": "https://flagcdn.com/w320/ci.png",
    "Haiti": "https://flagcdn.com/w320/ht.png",
    "Democratic Republic of the Congo": "https://flagcdn.com/w320/cd.png",
    "Namibia": "https://flagcdn.com/w320/na.png",
    "Togo": "https://flagcdn.com/w320/tg.png",
    "Zimbabwe": "https://flagcdn.com/w320/zw.png",
}

# 5. Color principal real de cada bandera
flag_colors = {
    "Sierra Leone":                     "#1EB53A",
    "Central African Republic":         "#003082",
    "Chad":                             "#002664",
    "Nigeria":                          "#008751",
    "Lesotho":                          "#009543",
    "Côte d'Ivoire":                    "#F77F00",
    "Swaziland":                        "#3E5EB9",
    "Angola":                           "#CC0000",
    "Cameroon":                         "#007A5E",
    "Somalia":                          "#4189DD",
    "Guinea-Bissau":                    "#CE1126",
    "Mozambique":                       "#009A44",
    "Mali":                             "#14B53A",
    "Zambia":                           "#198A00",
    "Burkina Faso":                     "#EF2B2D",
    "Uganda":                           "#000000",
    "Malawi":                           "#000000",
    "Guinea":                           "#CE1126",
    "Congo":                            "#009543",
    "South Sudan":                      "#078930",
    "Burundi":                          "#CE1126",
    "Niger":                            "#E05206",
    "Benin":                            "#008751",
    "Equatorial Guinea":                "#3E9A00",
    "Haiti":                            "#00209F",
    "Democratic Republic of the Congo": "#007FFF",
    "Namibia":                          "#003580",
    "Togo":                             "#006A4E",
    "Zimbabwe":                         "#006400",
    "Lesotho":                          "#009543",
}

# 6. Función para obtener miniatura de bandera
def get_flag(country):
    try:
        url = flag_urls[country]
        response = requests.get(url, timeout=5)
        img = Image.open(BytesIO(response.content)).convert("RGB")
        img = img.resize((60, 38), Image.LANCZOS)
        return np.array(img)
    except:
        return None

# 7. Pre-cargar miniaturas
print("Descargando banderas...")
flag_thumbs = {c: get_flag(c) for c in countries}
print("Listo!")

# 8. Figura
fig, ax = plt.subplots(figsize=(16, 12))
plt.subplots_adjust(right=0.82)

for i, country in enumerate(countries):
    color = flag_colors.get(country, "#888888")
    thumb = flag_thumbs[country]

    ax.barh(i, life_exp[i], color=color, edgecolor="black", linewidth=0.8, height=0.7)

    ax.text(life_exp[i] + 0.2, i, f"{life_exp[i]:.1f}",
            va='center', ha='left', fontsize=9)

    if thumb is not None:
        im = OffsetImage(thumb, zoom=0.6)
        ab = AnnotationBbox(
            im,
            xy=(1, i),
            xycoords=('axes fraction', 'data'),
            box_alignment=(-0.2, 0.5),
            frameon=True,
            bboxprops=dict(edgecolor="gray", linewidth=0.6)
        )
        ax.add_artist(ab)

# 9. Ejes y formato
ax.set_yticks(range(len(countries)))
ax.set_yticklabels(countries, fontsize=9)
ax.set_xlabel("Expectativa de vida (años)", fontsize=11)
ax.set_title("Top 30 países con menor expectativa de vida (2015)", fontsize=13, fontweight='bold')
ax.invert_yaxis()
ax.set_xlim(0, max(life_exp) + 5)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.show()

# 1. Preparar el gráfico
import matplotlib.pyplot as plt
from matplotlib.offsetbox import OffsetImage, AnnotationBbox
from PIL import Image
import requests
from io import BytesIO
import numpy as np

# 2. Filtrar año 2015 y limpiar datos
df1_2015 = df1[df1['Year'] == 2015].dropna(subset=['Life expectancy'])

# Normalizar nombre
df1_2015['Country'] = df1_2015['Country'].str.strip()
df1_2015['Country'] = df1_2015['Country'].replace({
    "Côte d'Ivoire": "Cote d'Ivoire"
})

# 3. Ordenar ASCENDENTE (menor a mayor) y tomar 30
df1_bottom30 = df1_2015.sort_values(by='Life expectancy', ascending=True).head(30)
countries = df1_bottom30['Country'].tolist()
life_exp = df1_bottom30['Life expectancy'].tolist()

# 4. Diccionario de banderas
flag_urls = {
    "Sierra Leone": "https://flagcdn.com/w320/sl.png",
    "Central African Republic": "https://flagcdn.com/w320/cf.png",
    "Lesotho": "https://flagcdn.com/w320/ls.png",
    "Nigeria": "https://flagcdn.com/w320/ng.png",
    "Chad": "https://flagcdn.com/w320/td.png",
    "Cote d'Ivoire": "https://flagcdn.com/w320/ci.png",
    "Guinea-Bissau": "https://flagcdn.com/w320/gw.png",
    "Somalia": "https://flagcdn.com/w320/so.png",
    "South Sudan": "https://flagcdn.com/w320/ss.png",
    "Zimbabwe": "https://flagcdn.com/w320/zw.png",
    "Burundi": "https://flagcdn.com/w320/bi.png",
    "Mali": "https://flagcdn.com/w320/ml.png",
    "Cameroon": "https://flagcdn.com/w320/cm.png",
    "Mozambique": "https://flagcdn.com/w320/mz.png",
    "Democratic Republic of the Congo": "https://flagcdn.com/w320/cd.png",
    "Equatorial Guinea": "https://flagcdn.com/w320/gq.png",
    "Guinea": "https://flagcdn.com/w320/gn.png",
    "Benin": "https://flagcdn.com/w320/bj.png",
    "Burkina Faso": "https://flagcdn.com/w320/bf.png",
    "Uganda": "https://flagcdn.com/w320/ug.png",
    "Zambia": "https://flagcdn.com/w320/zm.png",
    "Niger": "https://flagcdn.com/w320/ne.png",
    "Angola": "https://flagcdn.com/w320/ao.png",
    "Togo": "https://flagcdn.com/w320/tg.png",
    "Malawi": "https://flagcdn.com/w320/mw.png",
    "Ethiopia": "https://flagcdn.com/w320/et.png",
    "Rwanda": "https://flagcdn.com/w320/rw.png",
    "Gabon": "https://flagcdn.com/w320/ga.png",
    "Senegal": "https://flagcdn.com/w320/sn.png",
    "Afghanistan": "https://flagcdn.com/w320/af.png",
    "Gambia": "https://flagcdn.com/w320/gm.png",
    "Liberia": "https://flagcdn.com/w320/lr.png",
    "United Republic of Tanzania": "https://flagcdn.com/w320/tz.png",
    "Swaziland": "https://flagcdn.com/w320/sz.png",
    "Congo": "https://flagcdn.com/w320/cg.png",
    "Papua New Guinea": "https://flagcdn.com/w320/pg.png",
    "Ghana": "https://flagcdn.com/w320/gh.png"
}

# 5. Colores principales
flag_colors = {
    "Sierra Leone": "#1EB53A",
    "Central African Republic": "#003082",
    "Lesotho": "#1E90FF",
    "Nigeria": "#008751",
    "Chad": "#002664",
    "Cote d'Ivoire": "#F77F00",
    "Guinea-Bissau": "#CE1126",
    "Somalia": "#4189DD",
    "South Sudan": "#0F47AF",
    "Zimbabwe": "#006400",
    "Burundi": "#1EB53A",
    "Mali": "#14B53A",
    "Cameroon": "#007A5E",
    "Mozambique": "#D21034",
    "Democratic Republic of the Congo": "#007FFF",
    "Equatorial Guinea": "#3E9A00",
    "Guinea": "#FCD116",
    "Benin": "#008751",
    "Burkina Faso": "#EF2B2D",
    "Uganda": "#FCDC04",
    "Zambia": "#198A00",
    "Niger": "#E15307",
    "Angola": "#CE1126",
    "Togo": "#006A4E",
    "Malawi": "#000000",
    "Ethiopia": "#078930",
    "Rwanda": "#00A1DE",
    "Gabon": "#009E60",
    "Senegal": "#00853F",
    "Afghanistan": "#000000",
    "Gambia": "#CE1126",
    "Liberia": "#002868",
    "United Republic of Tanzania": "#1EB53A",
    "Swaziland": "#3E5EB9",
    "Congo": "#009543",
    "Papua New Guinea": "#000000",
    "Ghana": "#CE1126"
}

# 6. Función bandera
def get_flag(country):
    try:
        url = flag_urls[country]
        response = requests.get(url, timeout=5)
        img = Image.open(BytesIO(response.content)).convert("RGB")
        img = img.resize((60, 38), Image.LANCZOS)
        return np.array(img)
    except:
        return None

# 7. Pre-cargar banderas
print("Descargando banderas...")
flag_thumbs = {c: get_flag(c) for c in countries}
print("Listo!")

# 8. Figura
fig, ax = plt.subplots(figsize=(16, 12))
plt.subplots_adjust(right=0.82)

for i, country in enumerate(countries):
    color = flag_colors.get(country, "#888888")
    thumb = flag_thumbs[country]

    ax.barh(i, life_exp[i], color=color, edgecolor="black", linewidth=0.8, height=0.7)

    ax.text(life_exp[i] + 0.2, i, f"{life_exp[i]:.1f}",
            va='center', ha='left', fontsize=9)

    if thumb is not None:
        im = OffsetImage(thumb, zoom=0.6)
        ab = AnnotationBbox(
            im,
            xy=(1, i),
            xycoords=('axes fraction', 'data'),
            box_alignment=(-0.2, 0.5),
            frameon=True,
            bboxprops=dict(edgecolor="gray", linewidth=0.6)
        )
        ax.add_artist(ab)

# 9. Estilo final
ax.set_yticks(range(len(countries)))
ax.set_yticklabels(countries, fontsize=9)
ax.set_xlabel("Expectativa de vida (años)", fontsize=11)
ax.set_title("30 países con menor expectativa de vida (2015)", fontsize=13, fontweight='bold')
ax.invert_yaxis()
ax.set_xlim(0, max(life_exp) + 5)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.show()

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

cols = [
    "Life expectancy",
    "Schooling",
    "GDP",
    "Adult Mortality",
    "infant deaths"
]

df1[cols] = scaler.fit_transform(df1[cols])

score = (
    df1["Life expectancy"] * 0.4
    + df1["Schooling"] * 0.1
    + df1["GDP"] * 0.3
    - df1["Adult Mortality"] * 0.1
    - df1["infant deaths"] * 0.1
)

df1["Score"] = score

# Filtrar año 2015
df1_2015 = df1[df1["Year"] == 2015]

# Top países según Score
top_paises = (
    df1_2015.groupby("Country")["Score"]
    .mean()
    .sort_values(ascending=False)
    .head(10)
)

print(top_paises)

# Filtrar año 2015
df1_2015 = df1[df1["Year"] == 2015]

# 10 países con menor Score
bottom_paises = (
    df1_2015.groupby("Country")["Score"]
    .mean()
    .sort_values(ascending=True)
    .head(10)
)

print(bottom_paises)

from sklearn.preprocessing import MinMaxScaler

cols = [
    "Hepatitis B",
    "Measles",
    "Diphtheria",
    "HIV/AIDS",
    "Polio"
]

scaler = MinMaxScaler()
df1[cols] = scaler.fit_transform(df1[cols])

score = (
    (1 - df1["Hepatitis B"]) * 0.2
    + df1["Measles"] * 0.2
    + (1 - df1["Diphtheria"]) * 0.2
    + df1["HIV/AIDS"] * 0.3
    + (1 - df1["Polio"]) * 0.1
)

df1["Enfermedades Score"] = (
    (1 - df1["Hepatitis B"]) * 0.2
    + df1["Measles"] * 0.2
    + (1 - df1["Diphtheria"]) * 0.2
    + df1["HIV/AIDS"] * 0.3
    + (1 - df1["Polio"]) * 0.1
)

# Columnas a revisar para valores cero
cols_to_filter = [
    "Hepatitis B",
    "Measles",
    "Diphtheria",
    "HIV/AIDS",
    "Polio"
]

# Filtrar df1 para eliminar filas donde cualquiera de las columnas seleccionadas es cero
df1 = df1[~(df1[cols_to_filter] == 0).any(axis=1)]

print(f"DataFrame df1 después de eliminar filas con ceros: {df1.shape[0]} filas")

# Volver a crear df1_2015 con los datos ya limpios
df1_2015 = df1[df1['Year'] == 2015]

# Columnas a mostrar
cols_to_display = ['Country', 'Hepatitis B', 'Measles', 'Diphtheria', 'HIV/AIDS', 'Polio', 'Enfermedades Score']

display(df1_2015[cols_to_display].sort_values("Enfermedades Score", ascending=False).head(10))

df1_2015 = df1[df1["Year"] == 2015]
df1.sort_values("Enfermedades Score", ascending=True).head(10)

df1_2015 = df1[df1['Year'] == 2015]
display(df1_2015.sort_values("Enfermedades Score", ascending=False).head(10))

cols_to_display = ['Country', 'Hepatitis B', 'Measles', 'Diphtheria', 'HIV/AIDS', 'Polio', 'Enfermedades Score']
display(df1_2015[cols_to_display].sort_values("Enfermedades Score", ascending=False).head(10))
df1 = df1[~(df1[cols] == 0).any(axis=1)]

cols_to_display = ['Country', 'Hepatitis B', 'Measles', 'Diphtheria', 'HIV/AIDS', 'Polio', 'Enfermedades Score']
display(df1_2015[cols_to_display].sort_values("Enfermedades Score", ascending=True).head(10))
df1 = df1[~(df1[cols] == 0).any(axis=1)]

# Mostrar filas que tengan al menos un 0 en las columnas seleccionadas

cols = [
    "Hepatitis B",
    "Measles",
    "Diphtheria",
    "HIV/AIDS",
    "Polio"
]

# Filas con algún 0
rows_with_zero = df1[(df1[cols] == 0).any(axis=1)]

# Agrupar por país y mostrar columnas con 0
for country, group in rows_with_zero.groupby("Country"):
    print(f"\n{country}")

    for index, row in group.iterrows():
        zero_cols = [col for col in cols if row[col] == 0]
        print("Columnas con 0:", zero_cols)

# =========================
# 1. IMPORTAR LIBRERÍAS
# =========================

import pandas as pd
from sklearn.preprocessing import MinMaxScaler
# =========================
# FILTRAR AÑO 2015
# =========================

df1 = df1[df1["Year"] == 2015]
# =========================
# 2. SELECCIONAR COLUMNAS
# =========================

cols = [
    "Hepatitis B",
    "Measles",
    "Diphtheria",
    "HIV/AIDS",
    "Polio"
]

# =========================
# 3. ELIMINAR NULOS
# =========================

df1 = df1.dropna(subset=cols)

# =========================
# 4. ELIMINAR SOLO CEROS
# EN VACUNACIÓN
# =========================

df1 = df1[
    (df1["Hepatitis B"] != 0) &
    (df1["Diphtheria"] != 0) &
    (df1["Polio"] != 0)
]

# =========================
# 5. NORMALIZAR VARIABLES
# =========================

scaler = MinMaxScaler()

df1[cols] = scaler.fit_transform(df1[cols])

# =========================
# 6. CREAR SCORE
# =========================

df1["Enfermedades Score"] = (
    (1 - df1["Hepatitis B"]) * 0.25
    + df1["Measles"] * 0.15
    + (1 - df1["Diphtheria"]) * 0.25
    + df1["HIV/AIDS"] * 0.25
    + (1 - df1["Polio"]) * 0.10
)

# =========================
# 7. ORDENAR RESULTADOS
# =========================

df1 = df1.sort_values(
    by="Enfermedades Score",
    ascending=False
)

# =========================
# 8. MOSTRAR RESULTADOS
# =========================

resultado = df1[
    [
        "Country",
        "Hepatitis B",
        "Measles",
        "Diphtheria",
        "HIV/AIDS",
        "Polio",
        "Enfermedades Score"
    ]
].head(20).copy()

# Convertir todas las variables normalizadas a porcentaje
columnas_pct = [
    "Hepatitis B",
    "Measles",
    "Diphtheria",
    "HIV/AIDS",
    "Polio",
    "Enfermedades Score"
]

resultado[columnas_pct] = (
    resultado[columnas_pct] * 100
).round(2)

# Renombrar columnas para que se vean más prolijas
resultado = resultado.rename(columns={
    "Country": "País",
    "Hepatitis B": "Hepatitis B (%)",
    "Measles": "Measles (%)",
    "Diphtheria": "Diphtheria (%)",
    "HIV/AIDS": "HIV/AIDS (%)",
    "Polio": "Polio (%)",
    "Enfermedades Score": "Score (%)"
})

display(resultado)

""" **segundo dataset**


"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df2 = pd.read_excel("2015.year.xlsx")

df2.head()

pd.merge(df1, df2, on='Country', how='inner')

pd.merge(df1, df2, on=['Country', 'Year'], how='inner')

pd.merge(df1, df2, on=['Country', 'Year'], how='right')

# ============================================
# GRÁFICO GDP HISTÓRICO + FORECAST 2025
# + PRECISIÓN DEL FORECAST
# ============================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# ============================================
# 1. CARGAR DATASETS
# ============================================

df1 = pd.read_csv("Life Expectancy Data.csv")
df2 = pd.read_excel("2015.year.xlsx")

# ============================================
# 2. LIMPIEZA
# ============================================

df1['GDP'] = pd.to_numeric(df1['GDP'], errors='coerce')

df1 = df1.dropna(subset=['GDP', 'Year'])

# ============================================
# 3. GDP PROMEDIO POR AÑO
# ============================================

df1_gdp_evolution = (
    df1.groupby('Year')['GDP']
    .mean()
    .reset_index()
)

# ============================================
# 4. TOMAR GDP DEL DF2
# ============================================

possible_gdp_cols = [
    col for col in df2.columns
    if 'gdp' in col.lower()
]

gdp_col_df2 = possible_gdp_cols[0]

df2[gdp_col_df2] = pd.to_numeric(
    df2[gdp_col_df2],
    errors='coerce'
)

df2_gdp_2015 = df2[gdp_col_df2].mean()

# ============================================
# 5. SUMAR EL GDP DEL DF2 AL 2015
# ============================================

mask_2015 = df1_gdp_evolution['Year'] == 2015

df1_gdp_evolution.loc[mask_2015, 'GDP'] = (
    df1_gdp_evolution.loc[mask_2015, 'GDP']
    + df2_gdp_2015
)

# ============================================
# 6. MODELO DE REGRESIÓN
# ============================================

X = df1_gdp_evolution[['Year']]
y = df1_gdp_evolution['GDP']

model = LinearRegression()
model.fit(X, y)

# ============================================
# 7. PREDICCIÓN HASTA 2025
# ============================================

future_years = np.arange(
    df1_gdp_evolution['Year'].max() + 1,
    2026
).reshape(-1, 1)

predicted_gdp = model.predict(future_years)

predictions_df = pd.DataFrame({
    'Year': future_years.flatten(),
    'GDP': predicted_gdp
})

# ============================================
# 7B. EXTENDER PREDICCIÓN DE 2026 A 2030
# ============================================

future_years_2030 = np.arange(2026, 2031).reshape(-1, 1)

predicted_gdp_2030 = model.predict(future_years_2030)

predictions_2030_df = pd.DataFrame({
    'Year': future_years_2030.flatten(),
    'GDP': predicted_gdp_2030
})

# ============================================
# 8. PRECISIÓN DEL FORECAST
# ============================================

gdp_pred_2025 = predictions_df.loc[
    predictions_df['Year'] == 2025,
    'GDP'
].values[0]

# CAMBIAR POR EL GDP REAL QUE UTILICEN
gdp_real_2025 = 14500

absolute_error = abs(
    gdp_real_2025 - gdp_pred_2025
)

percentage_error = (
    absolute_error / gdp_real_2025
) * 100

accuracy = 100 - percentage_error

# ============================================
# 9. UNIR ÚLTIMO PUNTO HISTÓRICO
# ============================================

last_historical = df1_gdp_evolution.iloc[-1:]

forecast_plot = pd.concat([
    last_historical,
    predictions_df
])

# ============================================
# 10. GRÁFICO
# ============================================

plt.style.use('dark_background')
plt.figure(figsize=(14,8))

# HISTÓRICO

plt.plot(
    df1_gdp_evolution['Year'],
    df1_gdp_evolution['GDP'],
    marker='o',
    linewidth=3,
    color='#6EA8FE',
    label='GDP Histórico'
)

# FORECAST

plt.plot(
    forecast_plot['Year'],
    forecast_plot['GDP'],
    marker='o',
    linestyle='--',
    linewidth=3,
    color='#FFD43B',
    label='Forecast GDP 2025'
)

# FORECAST 2026-2030

forecast_2030_plot = pd.concat([
    predictions_df[predictions_df['Year'] == 2025],
    predictions_2030_df
])

plt.plot(
    forecast_2030_plot['Year'],
    forecast_2030_plot['GDP'],
    marker='o',
    linestyle='--',
    linewidth=3,
    color='#B197FC',
    label='Forecast GDP 2030'
)

# ============================================
# ETIQUETAS DE LOS PUNTOS
# ============================================

for x, y in zip(
    df1_gdp_evolution['Year'],
    df1_gdp_evolution['GDP']
):
    plt.text(
        x,
        y,
        f'{y:.0f}',
        fontsize=10,
        color='white',
        ha='center',
        va='bottom'
    )

for x, y in zip(
    predictions_df['Year'],
    predictions_df['GDP']
):
    plt.text(
        x,
        y,
        f'{y:.0f}',
        fontsize=10,
        color='#FFD43B',
        ha='center',
        va='bottom'
    )

for x, y in zip(
    predictions_2030_df['Year'],
    predictions_2030_df['GDP']
):
    plt.text(
        x,
        y,
        f'{y:.0f}',
        fontsize=10,
        color='#B197FC',
        ha='center',
        va='bottom'
    )

# ============================================
# TÍTULO
# ============================================

plt.title(
    'Evolución Histórica + Forecast del GDP',
    fontsize=22,
    weight='bold'
)

# ============================================
# EJES
# ============================================

plt.xlabel(
    'Año',
    fontsize=15,
    weight='bold'
)

plt.ylabel(
    'GDP',
    fontsize=15,
    weight='bold'
)

# ============================================
# GRID
# ============================================

plt.grid(
    True,
    linestyle='--',
    alpha=0.3
)

# ============================================
# TICKS
# ============================================

plt.xticks(
    list(df1_gdp_evolution['Year']) +
    list(predictions_df['Year']),
    rotation=45
)

plt.xticks(
    list(df1_gdp_evolution['Year']) +
    list(predictions_df['Year']) +
    list(predictions_2030_df['Year']),
    rotation=45
)

# ============================================
# LEYENDA
# ============================================

plt.legend(fontsize=13)

# ============================================
# PRECISIÓN DEL FORECAST
# ============================================

plt.figtext(
    0.5,
    0.02,
    f'Precisión del Forecast 2025: {accuracy:.2f}% | Error: {percentage_error:.2f}%',
    ha='center',
    fontsize=12,
    color='white'
)

plt.tight_layout(rect=[0, 0.05, 1, 1])

plt.show()

# ============================================
# RESULTADOS
# ============================================

print("\n========= VALIDACIÓN DEL FORECAST =========")

print(f"GDP Predicho 2025 : {gdp_pred_2025:.2f}")
print(f"GDP Real 2025     : {gdp_real_2025:.2f}")

print(f"\nError absoluto    : {absolute_error:.2f}")
print(f"Error porcentual  : {percentage_error:.2f}%")

print(f"\nPrecisión del Forecast: {accuracy:.2f}%")

from google.colab import files
fig.write_html("grafico.html", full_html=True)
files.download('grafico.html')

# ============================================
# COMPARAR PREDICCIÓN VS GDP REAL 2025
# ============================================

# GDP predicho para 2025
gdp_pred_2025 = predictions_df.loc[
    predictions_df['Year'] == 2025,
    'GDP'
].values[0]

# ============================================
# INGRESA EL GDP REAL 2025
# (puedes buscarlo en World Bank, IMF, etc.)
# ============================================

gdp_real_2025 = 14500   # EJEMPLO

# ============================================
# ERROR ABSOLUTO
# ============================================

absolute_error = abs(gdp_real_2025 - gdp_pred_2025)

# ============================================
# ERROR PORCENTUAL
# ============================================

percentage_error = (
    absolute_error / gdp_real_2025
) * 100

# ============================================
# ACCURACY
# ============================================

accuracy = 100 - percentage_error

# ============================================
# RESULTADOS
# ============================================

print("\n========= VALIDACIÓN DEL FORECAST =========")

print(f"GDP Predicho 2025 : {gdp_pred_2025:.2f}")
print(f"GDP Real 2025     : {gdp_real_2025:.2f}")

print(f"\nError absoluto    : {absolute_error:.2f}")
print(f"Error porcentual  : {percentage_error:.2f}%")

print(f"\nAccuracy del modelo: {accuracy:.2f}%")

import matplotlib.pyplot as plt
import seaborn as sns

# Ensure df_merged is up-to-date and columns are renamed consistently
# This assumes df1 and df2 are already loaded and preprocessed as needed

# Strip whitespace from column names in both df1 and df2 for robust merging
df1.columns = df1.columns.str.strip()
df2.columns = df2.columns.str.strip()

df_merged = pd.merge(df1, df2, on=['Country', 'Year'], how='inner')

df_merged = df_merged.rename(columns={
    'Happiness Score': 'Happiness_Score',
    'Trust (Government Corruption)': 'Trust_Government_Corruption',
    'Economy (GDP per Capita)': 'Economy_GDP_per_Capita'
})

# Filter for the year 2015 and drop rows with missing values in the relevant columns
df_2015_economy_analysis = df_merged[df_merged['Year'] == 2015].dropna(subset=['Life expectancy', 'Economy_GDP_per_Capita', 'Region', 'Trust_Government_Corruption'])

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Economy_GDP_per_Capita', y='Life expectancy', data=df_2015_economy_analysis, hue='Region', size='Trust_Government_Corruption', sizes=(50, 500), alpha=0.7)
sns.regplot(x='Economy_GDP_per_Capita', y='Life expectancy', data=df_2015_economy_analysis, scatter=False, color='gray', line_kws={'linestyle': '--'})

plt.title('Life Expectancy vs. Economy (GDP per Capita) in 2015')
plt.xlabel('Economy (GDP per Capita)')
plt.ylabel('Life expectancy')
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.)
plt.tight_layout()
plt.show()

import plotly.express as px
from google.colab import files

# Strip whitespace from column names in both df1 and df2 for robust merging
df1.columns = df1.columns.str.strip()
df2.columns = df2.columns.str.strip()

# Merge df1 and df2 on 'Country' and 'Year'
df_merged = pd.merge(df1, df2, on=['Country', 'Year'], how='inner')

# Rename columns to match the plotting function's expectations
df_merged = df_merged.rename(columns={
    'Happiness Score': 'Happiness_Score',
    'Trust (Government Corruption)': 'Trust_Government_Corruption'
})

# Filter df_merged for the year 2015, as 'Happiness_Score' is only available for that year
df_2015_analysis = df_merged[df_merged['Year'] == 2015].dropna(subset=['Life expectancy', 'Happiness_Score', 'Region', 'GDP'])

fig = px.scatter(
    df_2015_analysis,
    x='Happiness_Score',
    y='Life expectancy',
    color='Region',
    size='GDP',
    hover_name='Country',
    hover_data=['Adult Mortality', 'Schooling', 'HIV/AIDS', 'Trust_Government_Corruption'],
    title='Expectativa de Vida vs. Puntuación de Felicidad en 2015 (Interactivo)',
    labels={
        'Happiness_Score': 'Puntuación de Felicidad',
        'Life expectancy': 'Expectativa de Vida',
        'GDP': 'PIB (en miles de USD)',
        'Adult Mortality': 'Mortalidad Adultos',
        'Schooling': 'Años de Escolaridad',
        'HIV/AIDS': 'Prevalencia HIV/SIDA',
        'Trust_Government_Corruption': 'Confianza en Gobierno (Corrupción)'
    }
)

fig.update_layout(showlegend=True) # Ensure legend is visible
fig.show()

# Save and download the plot
fig.write_html("grafico.html", full_html=True)
files.download('grafico.html')

from google.colab import files
fig.write_html("grafico.html", full_html=True)
files.download('grafico.html')

import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# =========================
# 1. FILTRAR 2015
# =========================

df1_2015 = df1[df1["Year"] == 2015].copy()
df2_2015 = df2[df2["Year"] == 2015].copy()

# =========================
# PREPARAR ENFERMEDADES SCORE PARA df1_2015
# =========================

# Define columns for score calculation
cols = [
    "Hepatitis B",
    "Measles",
    "Diphtheria",
    "HIV/AIDS",
    "Polio"
]

# Drop NaNs for these columns in df1_2015
df1_2015 = df1_2015.dropna(subset=cols)

# Filter out zeros for vaccination related columns
df1_2015 = df1_2015[
    (df1_2015["Hepatitis B"] != 0) &
    (df1_2015["Diphtheria"] != 0) &
    (df1_2015["Polio"] != 0)
]

# Normalize variables
scaler = MinMaxScaler()
df1_2015[cols] = scaler.fit_transform(df1_2015[cols])

# Create Enfermedades Score
df1_2015["Enfermedades Score"] = (
    (1 - df1_2015["Hepatitis B"]) * 0.25
    + df1_2015["Measles"] * 0.15
    + (1 - df1_2015["Diphtheria"]) * 0.25
    + df1_2015["HIV/AIDS"] * 0.25
    + (1 - df1_2015["Polio"]) * 0.10
)

# =========================
# ELIMINAR SCORES EN 0 O CASI CERO
# =========================
df1_2015 = df1_2015[
    df1_2015["Enfermedades Score"] > 0.001
]
# =========================
# 2. UNIR DATASETS
# =========================

df = pd.merge(
    df1_2015,
    df2_2015[["Country", "Happiness Score"]],
    on="Country",
    how="inner"
)

# =========================
# 3. ELIMINAR FALTANTES
# =========================

df = df.dropna(
    subset=[
        "Enfermedades Score",
        "Happiness Score"
    ]
)

# =========================
# 4. NORMALIZAR FELICIDAD
# =========================

scaler = MinMaxScaler()

df["Happiness Score"] = scaler.fit_transform(
    df[["Happiness Score"]]
)

# =========================
# 5. CREAR FELICIDAD SCORE
# =========================

df["Felicidad Score"] = df["Happiness Score"]

# =========================
# 6. ELIMINAR CEROS
# =========================

df = df[
    (df["Felicidad Score"] > 0)
]

# =========================
# 7. CREAR BIENESTAR Y SALUD SCORE
# =========================

df["Bienestar y Salud Score"] = (
    df["Felicidad Score"]
    - df["Enfermedades Score"]
)

# =========================
# 8. ORDENAR
# =========================

df = df.sort_values(
    by="Bienestar y Salud Score",
    ascending=False
)

# =========================
# 9. TABLA FINAL
# =========================

resultado = df[
    [
        "Country",
        "Enfermedades Score",
        "Felicidad Score",
        "Bienestar y Salud Score"
    ]
].head(20).copy()

# =========================
# 10. AGREGAR PORCENTAJES
# =========================

resultado["Enfermedades Score (%)"] = (
    resultado["Enfermedades Score"] * 100
).round(2)

resultado["Felicidad Score (%)"] = (
    resultado["Felicidad Score"] * 100
).round(2)

resultado["Bienestar y Salud Score (%)"] = (
    resultado["Bienestar y Salud Score"] * 100
).round(2)

# =========================
# 11. REDONDEAR SCORES
# =========================

resultado["Enfermedades Score"] = (
    resultado["Enfermedades Score"]
).round(4)

resultado["Felicidad Score"] = (
    resultado["Felicidad Score"]
).round(4)

resultado["Bienestar y Salud Score"] = (
    resultado["Bienestar y Salud Score"]
).round(4)

# =========================
# 12. RENOMBRAR COLUMNAS
# =========================

resultado = resultado.rename(columns={
    "Country": "País"
})

display(resultado)

print(f"Cantidad de países analizados: {df['Country'].nunique()}")

promedio_mundial = df["Bienestar y Salud Score"].mean()

mejor_pais = df.loc[df["Bienestar y Salud Score"].idxmax()]
peor_pais = df.loc[df["Bienestar y Salud Score"].idxmin()]

gabon = df[df["Country"] == "Gabon"]

print(f"Países analizados: {df['Country'].nunique()}")

print(f"\nPromedio mundial: {promedio_mundial:.4f}".replace(".", ","))
print(f"Promedio mundial (%): {(promedio_mundial*100):.2f}%".replace(".", ","))

print(f"\nMejor país: {mejor_pais['Country']}")
print(f"Score: {mejor_pais['Bienestar y Salud Score']:.4f}".replace(".", ","))
print(f"Score (%): {(mejor_pais['Bienestar y Salud Score']*100):.2f}%".replace(".", ","))

print(f"\nPeor país: {peor_pais['Country']}")
print(f"Score: {peor_pais['Bienestar y Salud Score']:.4f}".replace(".", ","))
print(f"Score (%): {(peor_pais['Bienestar y Salud Score']*100):.2f}%".replace(".", ","))

import pandas as pd
import plotly.express as px

# =========================
# TOP 5 MEJORES Y PEORES
# =========================

top5 = df.nlargest(
    5,
    "Bienestar y Salud Score"
)

bottom5 = df.nsmallest(
    5,
    "Bienestar y Salud Score"
)

grafico_df = pd.concat(
    [top5, bottom5]
)

grafico_df = grafico_df.sort_values(
    "Bienestar y Salud Score"
)

# =========================
# BANDERAS
# =========================

banderas = {
    "Netherlands": "🇳🇱",
    "Israel": "🇮🇱",
    "Australia": "🇦🇺",
    "New Zealand": "🇳🇿",
    "Austria": "🇦🇹",
    "Mozambique": "🇲🇿",
    "Chad": "🇹🇩",
    "Swaziland": "🇸🇿",
    "Central African Republic": "🇨🇫",
    "Gabon": "🇬🇦"
}

grafico_df["Bandera"] = grafico_df["Country"].map(banderas)

# =========================
# SCORE EN PORCENTAJE
# =========================

grafico_df["Score (%)"] = (
    grafico_df["Bienestar y Salud Score"] * 100
).round(2)

# =========================
# GRÁFICO INTERACTIVO
# =========================

fig = px.bar(
    grafico_df,
    x="Score (%)",
    y="Country",
    orientation="h",
    color="Bienestar y Salud Score",
    text="Score (%)",
    color_continuous_scale="RdYlGn",
    title="Top 5 Mejores y Top 5 Peores Países según Bienestar y Salud (2015)",
    custom_data=[
        "Bandera",
        "Country",
        "Bienestar y Salud Score",
        "Score (%)"
    ]
)

# =========================
# HOVER PERSONALIZADO
# =========================

fig.update_traces(
    hovertemplate=
    "<b>%{customdata[0]} %{customdata[1]}</b><br><br>" +
    "Score: %{customdata[2]:.4f}<br>" +
    "Score (%): %{customdata[3]:.2f}%<extra></extra>",

    texttemplate="%{text:.2f}%",
    textposition="outside"
)

# =========================
# DISEÑO
# =========================

fig.update_layout(
    xaxis_title="Bienestar y Salud Score (%)",
    yaxis_title="País",
    template="plotly_white",
    height=700,
    title_x=0.5
)

fig.show()

from google.colab import files
fig.write_html("grafico.html", full_html=True)
files.download('grafico.html')

!pip -q install country_converter requests openpyxl

import os
import base64
import requests
import pandas as pd
import numpy as np
import plotly.express as px
import country_converter as coco
from google.colab import files
from IPython.display import HTML, display

# ============================================
# 2. LIMPIAR COLUMNAS Y DATOS
# ============================================

df1.columns = df1.columns.str.strip()
df2.columns = df2.columns.str.strip()

df1['Country'] = df1['Country'].astype(str).str.strip()
df2['Country'] = df2['Country'].astype(str).str.strip()

if 'Year' not in df2.columns:
    df2['Year'] = 2015

df1['Year'] = pd.to_numeric(df1['Year'], errors='coerce')
df2['Year'] = pd.to_numeric(df2['Year'], errors='coerce')

# ============================================
# 3. MERGE ENTRE DATASETS
# ============================================

df_merged = pd.merge(
    df1,
    df2,
    on=['Country', 'Year'],
    how='inner'
)

# ============================================
# 4. RENOMBRAR COLUMNAS
# ============================================

df_merged = df_merged.rename(columns={
    'Happiness Score': 'Happiness_Score',
    'Trust (Government Corruption)': 'Trust_Government_Corruption'
})

if 'GDP' not in df_merged.columns:
    if 'GDP_x' in df_merged.columns:
        df_merged = df_merged.rename(columns={'GDP_x': 'GDP'})
    elif 'GDP_y' in df_merged.columns:
        df_merged = df_merged.rename(columns={'GDP_y': 'GDP'})

if 'Region' not in df_merged.columns:
    region_cols = [c for c in df_merged.columns if 'Region' in c]
    if len(region_cols) > 0:
        df_merged = df_merged.rename(columns={region_cols[0]: 'Region'})

df_merged['GDP'] = pd.to_numeric(df_merged['GDP'], errors='coerce')
df_merged['Life expectancy'] = pd.to_numeric(df_merged['Life expectancy'], errors='coerce')
df_merged['Happiness_Score'] = pd.to_numeric(df_merged['Happiness_Score'], errors='coerce')

# ============================================
# 5. FILTRAR AÑO 2015
# ============================================

df_2015_analysis = df_merged[
    df_merged['Year'] == 2015
].dropna(
    subset=[
        'Country',
        'Life expectancy',
        'Happiness_Score',
        'Region',
        'GDP'
    ]
).copy()

# ============================================
# 6. CREAR CONTINENTES + ISO2
# ============================================

cc = coco.CountryConverter()

country_name_fix = {
    'Russia': 'Russian Federation',
    'South Korea': 'Korea, Republic of',
    'North Korea': "Korea, Democratic People's Republic of",
    'Iran': 'Iran, Islamic Republic of',
    'Syria': 'Syrian Arab Republic',
    'Vietnam': 'Viet Nam',
    'Tanzania': 'Tanzania, United Republic of',
    'Moldova': 'Moldova, Republic of',
    'Bolivia': 'Bolivia, Plurinational State of',
    'Venezuela': 'Venezuela, Bolivarian Republic of',
    'Laos': "Lao People's Democratic Republic",
    'Czech Republic': 'Czechia',
    'Ivory Coast': "Côte d'Ivoire",
    'Palestinian Territories': 'Palestine, State of',
    'Congo (Kinshasa)': 'Congo, The Democratic Republic of the',
    'Congo (Brazzaville)': 'Congo',
    'Macedonia': 'North Macedonia',
    'Taiwan': 'Taiwan, Province of China',
    'United States': 'United States of America',
    'United Kingdom': 'United Kingdom of Great Britain and Northern Ireland',
    'Somaliland region': 'Somalia',
    'Hong Kong': 'Hong Kong',
    'Swaziland': 'Eswatini',
    'North Cyprus': 'Cyprus',
    'Kosovo': 'Kosovo'
}

manual_iso2 = {
    'Taiwan': 'TW',
    'Hong Kong': 'HK',
    'Kosovo': 'XK',
    'North Cyprus': 'CY',
    'Somaliland region': 'SO',
    'Palestinian Territories': 'PS',
    'Congo (Kinshasa)': 'CD',
    'Congo (Brazzaville)': 'CG',
    'Ivory Coast': 'CI',
    'Macedonia': 'MK',
    'Czech Republic': 'CZ',
    'Laos': 'LA',
    'Vietnam': 'VN',
    'South Korea': 'KR',
    'North Korea': 'KP',
    'Russia': 'RU',
    'Iran': 'IR',
    'Syria': 'SY',
    'Tanzania': 'TZ',
    'Moldova': 'MD',
    'Bolivia': 'BO',
    'Venezuela': 'VE',
    'Swaziland': 'SZ'
}

manual_continent = {
    'Taiwan': 'Asia',
    'Hong Kong': 'Asia',
    'Kosovo': 'Europe',
    'North Cyprus': 'Asia',
    'Somaliland region': 'Africa',
    'Palestinian Territories': 'Asia',
    'Congo (Kinshasa)': 'Africa',
    'Congo (Brazzaville)': 'Africa',
    'Ivory Coast': 'Africa',
    'Macedonia': 'Europe',
    'Czech Republic': 'Europe',
    'Laos': 'Asia',
    'Vietnam': 'Asia',
    'South Korea': 'Asia',
    'North Korea': 'Asia',
    'Russia': 'Europe',
    'Iran': 'Asia',
    'Syria': 'Asia',
    'Tanzania': 'Africa',
    'Moldova': 'Europe',
    'Bolivia': 'America',
    'Venezuela': 'America',
    'Swaziland': 'Africa'
}

df_2015_analysis['Country_clean'] = df_2015_analysis['Country'].replace(country_name_fix)

df_2015_analysis['ISO2'] = cc.convert(
    names=df_2015_analysis['Country_clean'].tolist(),
    to='ISO2',
    not_found='not found'
)

df_2015_analysis['Continent'] = cc.convert(
    names=df_2015_analysis['Country_clean'].tolist(),
    to='continent',
    not_found='not found'
)

for country, iso in manual_iso2.items():
    df_2015_analysis.loc[
        df_2015_analysis['Country'] == country,
        'ISO2'
    ] = iso

for country, continent in manual_continent.items():
    df_2015_analysis.loc[
        df_2015_analysis['Country'] == country,
        'Continent'
    ] = continent

continent_translation = {
    'Africa': 'África',
    'Asia': 'Asia',
    'Europe': 'Europa',
    'America': 'América',
    'Americas': 'América',
    'North America': 'América',
    'South America': 'América',
    'Oceania': 'Oceanía',
    'not found': 'Otros'
}

df_2015_analysis['Continent'] = df_2015_analysis['Continent'].replace(continent_translation)

df_2015_analysis['ISO2'] = df_2015_analysis['ISO2'].replace('not found', '')
df_2015_analysis['Continent'] = df_2015_analysis['Continent'].replace('not found', 'Otros')

# ============================================
# 7. DESCARGAR BANDERAS PARA USARLAS SOLO EN HOVER
# ============================================

flag_cache = {}

def get_flag_base64(iso2):
    if pd.isna(iso2):
        return ""

    iso2 = str(iso2).strip().lower()

    if iso2 == "" or iso2 == "not found":
        return ""

    if iso2 in flag_cache:
        return flag_cache[iso2]

    urls = [
        f"https://flagcdn.com/w80/{iso2}.png",
        f"https://flagcdn.com/w160/{iso2}.png"
    ]

    headers = {
        "User-Agent": "Mozilla/5.0"
    }

    for url in urls:
        try:
            response = requests.get(url, headers=headers, timeout=15)

            if response.status_code == 200 and len(response.content) > 500:
                encoded = base64.b64encode(response.content).decode("utf-8")
                flag_source = f"data:image/png;base64,{encoded}"
                flag_cache[iso2] = flag_source
                return flag_source

        except Exception:
            pass

    fallback = f"https://flagcdn.com/w80/{iso2}.png"
    flag_cache[iso2] = fallback
    return fallback

df_2015_analysis['Flag_Source'] = df_2015_analysis['ISO2'].apply(get_flag_base64)

# ============================================
# 8. ASEGURAR COLUMNAS PARA EL HOVER
# ============================================

needed_hover_cols = [
    'Adult Mortality',
    'Schooling',
    'HIV/AIDS',
    'Trust_Government_Corruption'
]

for col in needed_hover_cols:
    if col not in df_2015_analysis.columns:
        df_2015_analysis[col] = np.nan

# ============================================
# 9. COLORES POR CONTINENTE
# ============================================

continent_colors = {
    'África': '#EF553B',
    'América': '#00CC96',
    'Asia': '#AB63FA',
    'Europa': '#636EFA',
    'Oceanía': '#FFA15A',
    'Otros': '#A0A0A0'
}

# ============================================
# 10. CREAR GRÁFICO
# ============================================

fig = px.scatter(
    df_2015_analysis,
    x='Happiness_Score',
    y='Life expectancy',
    color='Continent',
    size='GDP',
    size_max=55,
    custom_data=[
        'Country',
        'Flag_Source',
        'Continent',
        'Region',
        'GDP',
        'Adult Mortality',
        'Schooling',
        'HIV/AIDS',
        'Trust_Government_Corruption'
    ],
    color_discrete_map=continent_colors,
    category_orders={
        'Continent': ['África', 'América', 'Asia', 'Europa', 'Oceanía', 'Otros']
    },
    title='Expectativa de Vida vs. Puntuación de Felicidad',
    labels={
        'Happiness_Score': 'Puntuación de Felicidad',
        'Life expectancy': 'Expectativa de Vida',
        'GDP': 'PIB',
        'Continent': 'Continente'
    }
)

fig.update_traces(
    hoverinfo='none',
    hovertemplate=None,
    marker=dict(
        opacity=0.78,
        line=dict(
            width=1,
            color='white'
        )
    )
)

fig.update_layout(
    template='plotly_dark',
    width=1100,
    height=720,
    hovermode='closest',
    title=dict(
        x=0.5,
        font=dict(
            size=23,
            color='white'
        )
    ),
    legend=dict(
        title='Continente',
        font=dict(size=13),
        bgcolor='rgba(0,0,0,0.35)',
        bordercolor='rgba(255,255,255,0.25)',
        borderwidth=1
    ),
    plot_bgcolor='rgb(10,10,10)',
    paper_bgcolor='rgb(10,10,10)',
    margin=dict(
        l=90,
        r=40,
        t=90,
        b=80
    )
)

fig.update_xaxes(
    title_text='Puntuación de Felicidad',
    showgrid=True,
    gridcolor='rgba(255,255,255,0.18)',
    zeroline=False,
    title_font=dict(size=16),
    tickfont=dict(size=12)
)

fig.update_yaxes(
    title_text='Expectativa de Vida',
    showgrid=True,
    gridcolor='rgba(255,255,255,0.18)',
    zeroline=False,
    title_font=dict(size=16),
    tickfont=dict(size=12)
)

# ============================================
# 11. TOOLTIP PERSONALIZADO CON BANDERA
# ============================================

post_script = """
(function() {
    const plot = document.getElementById('{plot_id}');

    const tooltip = document.createElement('div');
    tooltip.id = 'custom-flag-tooltip';
    tooltip.style.position = 'fixed';
    tooltip.style.display = 'none';
    tooltip.style.pointerEvents = 'none';
    tooltip.style.zIndex = '999999';
    tooltip.style.background = 'rgba(18, 18, 18, 0.96)';
    tooltip.style.color = 'white';
    tooltip.style.border = '1px solid rgba(255, 255, 255, 0.35)';
    tooltip.style.borderRadius = '12px';
    tooltip.style.padding = '12px 14px';
    tooltip.style.boxShadow = '0 8px 24px rgba(0,0,0,0.45)';
    tooltip.style.fontFamily = 'Arial, sans-serif';
    tooltip.style.fontSize = '13px';
    tooltip.style.lineHeight = '1.4';
    tooltip.style.minWidth = '260px';
    tooltip.style.maxWidth = '340px';
    document.body.appendChild(tooltip);

    function escapeHtml(value) {
        if (value === null || value === undefined) return 'Sin dato';
        return String(value)
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#039;');
    }

    function formatNumber(value, digits) {
        const num = Number(value);

        if (!Number.isFinite(num)) {
            return 'Sin dato';
        }

        return num.toLocaleString('es-AR', {
            minimumFractionDigits: digits,
            maximumFractionDigits: digits
        });
    }

    function moveTooltip(event) {
        if (!event) return;

        const offsetX = 18;
        const offsetY = 18;

        let left = event.clientX + offsetX;
        let top = event.clientY + offsetY;

        const rect = tooltip.getBoundingClientRect();

        if (left + rect.width > window.innerWidth - 12) {
            left = event.clientX - rect.width - offsetX;
        }

        if (top + rect.height > window.innerHeight - 12) {
            top = event.clientY - rect.height - offsetY;
        }

        tooltip.style.left = left + 'px';
        tooltip.style.top = top + 'px';
    }

    plot.on('plotly_hover', function(data) {
        const point = data.points[0];
        const cd = point.customdata;

        const country = escapeHtml(cd[0]);
        const flag = cd[1];
        const continent = escapeHtml(cd[2]);
        const region = escapeHtml(cd[3]);
        const gdp = formatNumber(cd[4], 2);
        const adultMortality = formatNumber(cd[5], 2);
        const schooling = formatNumber(cd[6], 2);
        const hiv = formatNumber(cd[7], 2);
        const trust = formatNumber(cd[8], 3);
        const happiness = formatNumber(point.x, 2);
        const life = formatNumber(point.y, 2);

        let flagHtml = '';

        if (flag && String(flag).length > 5) {
            flagHtml = `
                <img
                    src="${flag}"
                    style="
                        width: 34px;
                        height: 23px;
                        object-fit: cover;
                        border-radius: 3px;
                        border: 1px solid rgba(255,255,255,0.45);
                        margin-right: 9px;
                        vertical-align: middle;
                    "
                >
            `;
        }

        tooltip.innerHTML = `
            <div style="
                display: flex;
                align-items: center;
                margin-bottom: 8px;
                padding-bottom: 8px;
                border-bottom: 1px solid rgba(255,255,255,0.18);
            ">
                ${flagHtml}
                <div style="font-size: 16px; font-weight: 700;">
                    ${country}
                </div>
            </div>

            <div>
                <b>Continente:</b> ${continent}<br>
                <b>Región original:</b> ${region}<br>
                <b>Puntuación de felicidad:</b> ${happiness}<br>
                <b>Expectativa de vida:</b> ${life}<br>
                <b>GDP:</b> ${gdp}<br>
                <b>Mortalidad adultos:</b> ${adultMortality}<br>
                <b>Años de escolaridad:</b> ${schooling}<br>
                <b>HIV/SIDA:</b> ${hiv}<br>
                <b>Confianza gobierno/corrupción:</b> ${trust}
            </div>
        `;

        tooltip.style.display = 'block';
        moveTooltip(data.event);
    });

    plot.on('plotly_unhover', function() {
        tooltip.style.display = 'none';
    });

    plot.addEventListener('mousemove', function(event) {
        if (tooltip.style.display === 'block') {
            moveTooltip(event);
        }
    });

})();
"""

# ============================================
# 12. GENERAR HTML CON TOOLTIP PERSONALIZADO
# ============================================

html_string = fig.to_html(
    full_html=True,
    include_plotlyjs=True,
    div_id='grafico_continentes_banderas_hover',
    post_script=post_script,
    config={
        'displayModeBar': True,
        'scrollZoom': True,
        'responsive': True
    }
)

# ============================================
# 13. MOSTRAR EN COLAB
# ============================================

display(HTML(html_string))

# ============================================
# 14. GUARDAR Y DESCARGAR
# ============================================

output_file = "Gráfico Expectativa de Vida vs Felicidad.html"

with open(output_file, "w", encoding="utf-8") as f:
    f.write(html_string)

files.download(output_file)